PolyDEAL: dealii::MGTwoLevelTransferAgglomeration< dim, VectorType > Class Template Reference
dealii::MGTwoLevelTransferAgglomeration< dim, VectorType > Class Template Reference
#include <multigrid_utils.h>
Public Member Functions
MGTwoLevelTransferAgglomeration (const RtreeInfo< dim > &rtree_info)
void reinit (const AgglomerationHandler< dim > &agglo_handler_fine, const AgglomerationHandler< dim > &agglo_handler_coarse)
~MGTwoLevelTransferAgglomeration ()=default
void clear ()
virtual void prolongate (VectorType &dst, const VectorType &src) const
virtual void prolongate_and_add (VectorType &dst, const VectorType &src) const
virtual void restrict_and_add (VectorType &dst, const VectorType &src) const
Public Member Functions inherited from Subscriptor
Subscriptor ()
Subscriptor (const Subscriptor &)
Subscriptor (Subscriptor &&) noexcept
virtual ~Subscriptor ()
Subscriptor & operator= (const Subscriptor &)
Subscriptor & operator= (Subscriptor &&) noexcept
void serialize (Archive &ar, const unsigned int version)
void subscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
void unsubscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
unsigned int n_subscriptions () const
void list_subscribers (StreamType &stream) const
void list_subscribers () const
void subscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
void unsubscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
unsigned int n_subscriptions () const
void list_subscribers (StreamType &stream) const
void list_subscribers () const
Private Attributes
const AgglomerationHandler< dim > * agglo_handler_coarse
const AgglomerationHandler< dim > * agglo_handler_fine
std::vector< std::vector< unsigned int > > crss
std::vector< std::vector< typename Triangulation< dim >::active_cell_iterator > > agglomerates
std::shared_ptr< typename internal::MatrixSelectorAgglomeration< VectorType >::Sparsity > prolongation_sparsity
std::shared_ptr< typename internal::MatrixSelectorAgglomeration< VectorType >::Matrix > prolongation_matrix
Additional Inherited Members
Static Public Member Functions inherited from Subscriptor
static ::ExceptionBase & ExcInUse (int arg1, std::string arg2, std::string arg3)
static ::ExceptionBase & ExcNoSubscriber (std::string arg1, std::string arg2)
Detailed Description
template<int dim, typename VectorType>
class dealii::MGTwoLevelTransferAgglomeration< dim, VectorType >
Class implementing transfer between consecutive agglomerated levels.
Definition at line 286 of file multigrid_utils.h.
Constructor & Destructor Documentation
MGTwoLevelTransferAgglomeration()
template<int dim, typename VectorType > dealii::MGTwoLevelTransferAgglomeration< dim, VectorType >::MGTwoLevelTransferAgglomeration (const RtreeInfo< dim > & rtree_info)
Constructor.
Definition at line 395 of file multigrid_utils.h.
References dealii::MGTwoLevelTransferAgglomeration< dim, VectorType >::prolongation_matrix, and dealii::MGTwoLevelTransferAgglomeration< dim, VectorType >::prolongation_sparsity.
~MGTwoLevelTransferAgglomeration()
template<int dim, typename VectorType > dealii::MGTwoLevelTransferAgglomeration< dim, VectorType >::~MGTwoLevelTransferAgglomeration () default
Destructor.
Member Function Documentation
clear()
template<int dim, typename VectorType > void dealii::MGTwoLevelTransferAgglomeration< dim, VectorType >::clear ()
Reset the object.
Definition at line 619 of file multigrid_utils.h.
prolongate()
template<int dim, typename VectorType > void dealii::MGTwoLevelTransferAgglomeration< dim, VectorType >::prolongate (VectorType & dst, const VectorType & src) const virtual
Prolongate a vector from level to_level-1 to level to_level using the embedding matrices of the underlying finite element. The previous content of dst is overwritten.
Parameters
to_level The index of the level to prolongate to, which is the level of dst.
src is a vector with as many elements as there are degrees of freedom on the coarser level involved.
dst has as many elements as there are degrees of freedom on the finer level.
Definition at line 580 of file multigrid_utils.h.
prolongate_and_add()
template<int dim, typename VectorType > void dealii::MGTwoLevelTransferAgglomeration< dim, VectorType >::prolongate_and_add (VectorType & dst, const VectorType & src) const virtual
Definition at line 593 of file multigrid_utils.h.
reinit()
template<int dim, typename VectorType > void dealii::MGTwoLevelTransferAgglomeration< dim, VectorType >::reinit (const AgglomerationHandler< dim > & agglo_handler_fine, const AgglomerationHandler< dim > & agglo_handler_coarse)
Initialize transfer operator from coarse to fine level.
Definition at line 412 of file multigrid_utils.h.
References DynamicSparsityPattern::add_entries(), AffineConstraints< typename number >::close(), AffineConstraints< typename number >::distribute_local_to_global(), FiniteElement< int dim, int spacedim >::dofs_per_cell, DoFHandler< int dim, int spacedim >::get_fe(), DoFHandler< int dim, int spacedim >::n_dofs(), and p.
restrict_and_add()
template<int dim, typename VectorType > void dealii::MGTwoLevelTransferAgglomeration< dim, VectorType >::restrict_and_add (VectorType & dst, const VectorType & src) const virtual
Restrict a vector from level from_level to level from_level-1 using the transpose operation of the prolongate() method. If the region covered by cells on level from_level is smaller than that of level from_level-1 (local refinement), then some degrees of freedom in dst are active and will not be altered. For the other degrees of freedom, the result of the restriction is added.
Parameters
from_level The index of the level to restrict from, which is the level of src.
src is a vector with as many elements as there are degrees of freedom on the finer level involved.
dst has as many elements as there are degrees of freedom on the coarser level.
Definition at line 606 of file multigrid_utils.h.
Member Data Documentation
agglo_handler_coarse
template<int dim, typename VectorType > const AgglomerationHandler<dim>* dealii::MGTwoLevelTransferAgglomeration< dim, VectorType >::agglo_handler_coarse private
Pointer to coarse AgglomerationHandler
Definition at line 358 of file multigrid_utils.h.
agglo_handler_fine
template<int dim, typename VectorType > const AgglomerationHandler<dim>* dealii::MGTwoLevelTransferAgglomeration< dim, VectorType >::agglo_handler_fine private
Pointer to fine AgglomerationHandler
Definition at line 363 of file multigrid_utils.h.
agglomerates
template<int dim, typename VectorType > std::vector<std::vector<typename Triangulation<dim>::active_cell_iterator> > dealii::MGTwoLevelTransferAgglomeration< dim, VectorType >::agglomerates private
Agglomerates.
Definition at line 374 of file multigrid_utils.h.
crss
template<int dim, typename VectorType > std::vector<std::vector<unsigned int> > dealii::MGTwoLevelTransferAgglomeration< dim, VectorType >::crss private
CRS like data structure for every agglomerates.
Definition at line 368 of file multigrid_utils.h.
prolongation_matrix
template<int dim, typename VectorType > std::shared_ptr< typename internal::MatrixSelectorAgglomeration<VectorType>::Matrix> dealii::MGTwoLevelTransferAgglomeration< dim, VectorType >::prolongation_matrix private
The actual prolongation matrix. column indices belong to the dof indices of the coarse level, while row indices belong to the fine level.
Definition at line 389 of file multigrid_utils.h.
Referenced by dealii::MGTwoLevelTransferAgglomeration< dim, VectorType >::MGTwoLevelTransferAgglomeration().
prolongation_sparsity
template<int dim, typename VectorType > std::shared_ptr< typename internal::MatrixSelectorAgglomeration<VectorType>::Sparsity> dealii::MGTwoLevelTransferAgglomeration< dim, VectorType >::prolongation_sparsity private
Sparsity patterns for transfer matrices.
Definition at line 381 of file multigrid_utils.h.
Referenced by dealii::MGTwoLevelTransferAgglomeration< dim, VectorType >::MGTwoLevelTransferAgglomeration().
The documentation for this class was generated from the following file:
/github/workspace/include/multigrid_utils.h