PolyDEAL: FE_AggloDGP< dim, spacedim > Class Template Reference
FE_AggloDGP< dim, spacedim > Class Template Reference
Finite elements » Finite element space descriptions
#include <fe_agglodgp.h>
Public Member Functions
FE_AggloDGP (const unsigned int p)
virtual std::string get_name () const override
virtual void get_face_interpolation_matrix (const FiniteElement< dim, spacedim > &source, FullMatrix< double > &matrix, const unsigned int face_no=0) const override
virtual void get_subface_interpolation_matrix (const FiniteElement< dim, spacedim > &source, const unsigned int subface, FullMatrix< double > &matrix, const unsigned int face_no=0) const override
virtual bool has_support_on_face (const unsigned int shape_index, const unsigned int face_index) const override
virtual std::size_t memory_consumption () const override
virtual std::pair< Table< 2, bool >, std::vector< unsigned int > > get_constant_modes () const override
virtual std::unique_ptr< FiniteElement< dim, spacedim > > clone () const override
Functions to support hp
virtual std::vector< std::pair< unsigned int, unsigned int > > hp_vertex_dof_identities (const FiniteElement< dim, spacedim > &fe_other) const override
virtual std::vector< std::pair< unsigned int, unsigned int > > hp_line_dof_identities (const FiniteElement< dim, spacedim > &fe_other) const override
virtual std::vector< std::pair< unsigned int, unsigned int > > hp_quad_dof_identities (const FiniteElement< dim, spacedim > &fe_other, const unsigned int face_no=0) const override
virtual bool hp_constraints_are_implemented () const override
virtual FiniteElementDomination::Domination compare_for_domination (const FiniteElement< dim, spacedim > &fe_other, const unsigned int codim=0) const override final
Public Member Functions inherited from FE_Poly< dim, dim >
FE_Poly (const ScalarPolynomialsBase< dim > &poly_space, const FiniteElementData< dim > &fe_data, const std::vector< bool > &restriction_is_additive_flags, const std::vector< ComponentMask > &nonzero_components)
FE_Poly (const FE_Poly &fe)
unsigned int get_degree () const
virtual UpdateFlags requires_update_flags (const UpdateFlags update_flags) const override
const ScalarPolynomialsBase< dim > & get_poly_space () const
std::vector< unsigned int > get_poly_space_numbering () const
std::vector< unsigned int > get_poly_space_numbering_inverse () const
virtual double shape_value (const unsigned int i, const Point< dim > &p) const override
virtual double shape_value_component (const unsigned int i, const Point< dim > &p, const unsigned int component) const override
virtual Tensor< 1, dim > shape_grad (const unsigned int i, const Point< dim > &p) const override
virtual Tensor< 1, dim > shape_grad_component (const unsigned int i, const Point< dim > &p, const unsigned int component) const override
virtual Tensor< 2, dim > shape_grad_grad (const unsigned int i, const Point< dim > &p) const override
virtual Tensor< 2, dim > shape_grad_grad_component (const unsigned int i, const Point< dim > &p, const unsigned int component) const override
virtual Tensor< 3, dim > shape_3rd_derivative (const unsigned int i, const Point< dim > &p) const override
virtual Tensor< 3, dim > shape_3rd_derivative_component (const unsigned int i, const Point< dim > &p, const unsigned int component) const override
virtual Tensor< 4, dim > shape_4th_derivative (const unsigned int i, const Point< dim > &p) const override
virtual Tensor< 4, dim > shape_4th_derivative_component (const unsigned int i, const Point< dim > &p, const unsigned int component) const override
std::pair< std::unique_ptr< FiniteElement< dim, spacedim > >, unsigned int > operator^ (const unsigned int multiplicity) const
virtual bool operator== (const FiniteElement< dim, spacedim > &fe) const
bool operator== (const FiniteElementData &) const
bool operator!= (const FiniteElement< dim, spacedim > &) const
void serialize (Archive &ar, const unsigned int version)
ReferenceCell reference_cell () const
unsigned int n_unique_2d_subobjects () const
unsigned int n_unique_faces () const
unsigned int n_dofs_per_vertex () const
unsigned int n_dofs_per_line () const
unsigned int n_dofs_per_quad (unsigned int face_no=0) const
unsigned int max_dofs_per_quad () const
unsigned int n_dofs_per_hex () const
unsigned int n_dofs_per_face (unsigned int face_no=0, unsigned int child=0) const
unsigned int max_dofs_per_face () const
unsigned int n_dofs_per_cell () const
unsigned int n_dofs_per_object (const unsigned int i=0) const
unsigned int n_components () const
unsigned int n_blocks () const
const BlockIndices & block_indices () const
unsigned int tensor_degree () const
bool conforms (const Conformity) const
unsigned int get_first_line_index () const
unsigned int get_first_quad_index (const unsigned int quad_no=0) const
unsigned int get_first_hex_index () const
unsigned int get_first_face_line_index (const unsigned int face_no=0) const
unsigned int get_first_face_quad_index (const unsigned int face_no=0) const
virtual const FullMatrix< double > & get_restriction_matrix (const unsigned int child, const RefinementCase< dim > &refinement_case=RefinementCase< dim >::isotropic_refinement) const
virtual const FullMatrix< double > & get_restriction_matrix (const unsigned int child, const RefinementCase< dim > &refinement_case=RefinementCase< dim >::isotropic_refinement) const
virtual const FullMatrix< double > & get_prolongation_matrix (const unsigned int child, const RefinementCase< dim > &refinement_case=RefinementCase< dim >::isotropic_refinement) const
virtual const FullMatrix< double > & get_prolongation_matrix (const unsigned int child, const RefinementCase< dim > &refinement_case=RefinementCase< dim >::isotropic_refinement) const
bool prolongation_is_implemented () const
bool prolongation_is_implemented () const
bool isotropic_prolongation_is_implemented () const
bool isotropic_prolongation_is_implemented () const
bool restriction_is_implemented () const
bool restriction_is_implemented () const
bool isotropic_restriction_is_implemented () const
bool isotropic_restriction_is_implemented () const
bool restriction_is_additive (const unsigned int index) const
bool restriction_is_additive (const unsigned int index) const
const FullMatrix< double > & constraints (const ::internal::SubfaceCase< dim > &subface_case=::internal::SubfaceCase< dim >::case_isotropic) const
const FullMatrix< double > & constraints (const ::internal::SubfaceCase< dim > &subface_case=::internal::SubfaceCase< dim >::case_isotropic) const
bool constraints_are_implemented (const ::internal::SubfaceCase< dim > &subface_case=::internal::SubfaceCase< dim >::case_isotropic) const
bool constraints_are_implemented (const ::internal::SubfaceCase< dim > &subface_case=::internal::SubfaceCase< dim >::case_isotropic) const
virtual void get_interpolation_matrix (const FiniteElement< dim, spacedim > &source, FullMatrix< double > &matrix) const
virtual void get_interpolation_matrix (const FiniteElement< dim, spacedim > &source, FullMatrix< double > &matrix) const
std::pair< unsigned int, unsigned int > system_to_component_index (const unsigned int index) const
std::pair< unsigned int, unsigned int > system_to_component_index (const unsigned int index) const
unsigned int component_to_system_index (const unsigned int component, const unsigned int index) const
unsigned int component_to_system_index (const unsigned int component, const unsigned int index) const
std::pair< unsigned int, unsigned int > face_system_to_component_index (const unsigned int index, const unsigned int face_no=0) const
std::pair< unsigned int, unsigned int > face_system_to_component_index (const unsigned int index, const unsigned int face_no=0) const
unsigned int adjust_quad_dof_index_for_face_orientation (const unsigned int index, const unsigned int face_no, const unsigned char combined_orientation) const
unsigned int adjust_quad_dof_index_for_face_orientation (const unsigned int index, const unsigned int face_no, const unsigned char combined_orientation) const
virtual unsigned int face_to_cell_index (const unsigned int face_dof_index, const unsigned int face, const unsigned char combined_orientation=ReferenceCell::default_combined_face_orientation()) const
virtual unsigned int face_to_cell_index (const unsigned int face_dof_index, const unsigned int face, const unsigned char combined_orientation=ReferenceCell::default_combined_face_orientation()) const
unsigned int adjust_line_dof_index_for_line_orientation (const unsigned int index, const unsigned char combined_orientation) const
unsigned int adjust_line_dof_index_for_line_orientation (const unsigned int index, const unsigned char combined_orientation) const
const ComponentMask & get_nonzero_components (const unsigned int i) const
const ComponentMask & get_nonzero_components (const unsigned int i) const
unsigned int n_nonzero_components (const unsigned int i) const
unsigned int n_nonzero_components (const unsigned int i) const
bool is_primitive () const
bool is_primitive (const unsigned int i) const
bool is_primitive () const
bool is_primitive (const unsigned int i) const
unsigned int n_base_elements () const
unsigned int n_base_elements () const
virtual const FiniteElement< dim, spacedim > & base_element (const unsigned int index) const
virtual const FiniteElement< dim, spacedim > & base_element (const unsigned int index) const
unsigned int element_multiplicity (const unsigned int index) const
unsigned int element_multiplicity (const unsigned int index) const
const FiniteElement< dim, spacedim > & get_sub_fe (const ComponentMask &mask) const
virtual const FiniteElement< dim, spacedim > & get_sub_fe (const unsigned int first_component, const unsigned int n_selected_components) const
const FiniteElement< dim, spacedim > & get_sub_fe (const ComponentMask &mask) const
virtual const FiniteElement< dim, spacedim > & get_sub_fe (const unsigned int first_component, const unsigned int n_selected_components) const
std::pair< std::pair< unsigned int, unsigned int >, unsigned int > system_to_base_index (const unsigned int index) const
std::pair< std::pair< unsigned int, unsigned int >, unsigned int > system_to_base_index (const unsigned int index) const
std::pair< std::pair< unsigned int, unsigned int >, unsigned int > face_system_to_base_index (const unsigned int index, const unsigned int face_no=0) const
std::pair< std::pair< unsigned int, unsigned int >, unsigned int > face_system_to_base_index (const unsigned int index, const unsigned int face_no=0) const
types::global_dof_index first_block_of_base (const unsigned int b) const
types::global_dof_index first_block_of_base (const unsigned int b) const
std::pair< unsigned int, unsigned int > component_to_base_index (const unsigned int component) const
std::pair< unsigned int, unsigned int > component_to_base_index (const unsigned int component) const
std::pair< unsigned int, unsigned int > block_to_base_index (const unsigned int block) const
std::pair< unsigned int, unsigned int > block_to_base_index (const unsigned int block) const
std::pair< unsigned int, types::global_dof_index > system_to_block_index (const unsigned int component) const
std::pair< unsigned int, types::global_dof_index > system_to_block_index (const unsigned int component) const
unsigned int component_to_block_index (const unsigned int component) const
unsigned int component_to_block_index (const unsigned int component) const
ComponentMask component_mask (const FEValuesExtractors::Scalar &scalar) const
ComponentMask component_mask (const FEValuesExtractors::Vector &vector) const
ComponentMask component_mask (const FEValuesExtractors::SymmetricTensor< 2 > &sym_tensor) const
ComponentMask component_mask (const BlockMask &block_mask) const
ComponentMask component_mask (const FEValuesExtractors::Scalar &scalar) const
ComponentMask component_mask (const FEValuesExtractors::Vector &vector) const
ComponentMask component_mask (const FEValuesExtractors::SymmetricTensor< 2 > &sym_tensor) const
ComponentMask component_mask (const BlockMask &block_mask) const
BlockMask block_mask (const FEValuesExtractors::Scalar &scalar) const
BlockMask block_mask (const FEValuesExtractors::Vector &vector) const
BlockMask block_mask (const FEValuesExtractors::SymmetricTensor< 2 > &sym_tensor) const
BlockMask block_mask (const ComponentMask &component_mask) const
BlockMask block_mask (const FEValuesExtractors::Scalar &scalar) const
BlockMask block_mask (const FEValuesExtractors::Vector &vector) const
BlockMask block_mask (const FEValuesExtractors::SymmetricTensor< 2 > &sym_tensor) const
BlockMask block_mask (const ComponentMask &component_mask) const
const std::vector< Point< dim > > & get_unit_support_points () const
const std::vector< Point< dim > > & get_unit_support_points () const
bool has_support_points () const
bool has_support_points () const
virtual Point< dim > unit_support_point (const unsigned int index) const
virtual Point< dim > unit_support_point (const unsigned int index) const
const std::vector< Point< dim - 1 > > & get_unit_face_support_points (const unsigned int face_no=0) const
const std::vector< Point< dim - 1 > > & get_unit_face_support_points (const unsigned int face_no=0) const
bool has_face_support_points (const unsigned int face_no=0) const
bool has_face_support_points (const unsigned int face_no=0) const
virtual Point< dim - 1 > unit_face_support_point (const unsigned int index, const unsigned int face_no=0) const
virtual Point< dim - 1 > unit_face_support_point (const unsigned int index, const unsigned int face_no=0) const
const std::vector< Point< dim > > & get_generalized_support_points () const
const std::vector< Point< dim > > & get_generalized_support_points () const
bool has_generalized_support_points () const
bool has_generalized_support_points () const
GeometryPrimitive get_associated_geometry_primitive (const unsigned int cell_dof_index) const
GeometryPrimitive get_associated_geometry_primitive (const unsigned int cell_dof_index) const
virtual void convert_generalized_support_point_values_to_dof_values (const std::vector< Vector< double > > &support_point_values, std::vector< double > &nodal_values) const
virtual void convert_generalized_support_point_values_to_dof_values (const std::vector< Vector< double > > &support_point_values, std::vector< double > &nodal_values) const
void subscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
void subscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
void unsubscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
void unsubscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
unsigned int n_subscriptions () const
unsigned int n_subscriptions () const
void list_subscribers (StreamType &stream) const
void list_subscribers () const
void list_subscribers (StreamType &stream) const
void list_subscribers () const
Public Member Functions inherited from FiniteElement< int dim, int spacedim >
FiniteElement (const FiniteElementData< dim > &fe_data, const std::vector< bool > &restriction_is_additive_flags, const std::vector< ComponentMask > &nonzero_components)
FiniteElement (FiniteElement< dim, spacedim > &&)=default
FiniteElement (const FiniteElement< dim, spacedim > &)=default
virtual ~FiniteElement () override=default
std::pair< std::unique_ptr< FiniteElement< dim, spacedim > >, unsigned int > operator^ (const unsigned int multiplicity) const
bool operator!= (const FiniteElement< dim, spacedim > &) const
void serialize (Archive &ar, const unsigned int version)
ReferenceCell reference_cell () const
unsigned int n_unique_2d_subobjects () const
unsigned int n_unique_faces () const
unsigned int n_dofs_per_vertex () const
unsigned int n_dofs_per_line () const
unsigned int n_dofs_per_quad (unsigned int face_no=0) const
unsigned int max_dofs_per_quad () const
unsigned int n_dofs_per_hex () const
unsigned int n_dofs_per_face (unsigned int face_no=0, unsigned int child=0) const
unsigned int max_dofs_per_face () const
unsigned int n_dofs_per_cell () const
unsigned int n_dofs_per_object (const unsigned int i=0) const
unsigned int n_components () const
unsigned int n_blocks () const
const BlockIndices & block_indices () const
unsigned int tensor_degree () const
bool conforms (const Conformity) const
bool operator== (const FiniteElementData &) const
unsigned int get_first_line_index () const
unsigned int get_first_quad_index (const unsigned int quad_no=0) const
unsigned int get_first_hex_index () const
unsigned int get_first_face_line_index (const unsigned int face_no=0) const
unsigned int get_first_face_quad_index (const unsigned int face_no=0) const
bool prolongation_is_implemented () const
bool isotropic_prolongation_is_implemented () const
bool restriction_is_implemented () const
bool isotropic_restriction_is_implemented () const
bool restriction_is_additive (const unsigned int index) const
const FullMatrix< double > & constraints (const ::internal::SubfaceCase< dim > &subface_case=::internal::SubfaceCase< dim >::case_isotropic) const
bool constraints_are_implemented (const ::internal::SubfaceCase< dim > &subface_case=::internal::SubfaceCase< dim >::case_isotropic) const
std::pair< unsigned int, unsigned int > system_to_component_index (const unsigned int index) const
unsigned int component_to_system_index (const unsigned int component, const unsigned int index) const
std::pair< unsigned int, unsigned int > face_system_to_component_index (const unsigned int index, const unsigned int face_no=0) const
unsigned int adjust_quad_dof_index_for_face_orientation (const unsigned int index, const unsigned int face_no, const unsigned char combined_orientation) const
unsigned int adjust_line_dof_index_for_line_orientation (const unsigned int index, const unsigned char combined_orientation) const
const ComponentMask & get_nonzero_components (const unsigned int i) const
unsigned int n_nonzero_components (const unsigned int i) const
bool is_primitive () const
bool is_primitive (const unsigned int i) const
unsigned int n_base_elements () const
unsigned int element_multiplicity (const unsigned int index) const
const FiniteElement< dim, spacedim > & get_sub_fe (const ComponentMask &mask) const
std::pair< std::pair< unsigned int, unsigned int >, unsigned int > system_to_base_index (const unsigned int index) const
std::pair< std::pair< unsigned int, unsigned int >, unsigned int > face_system_to_base_index (const unsigned int index, const unsigned int face_no=0) const
types::global_dof_index first_block_of_base (const unsigned int b) const
std::pair< unsigned int, unsigned int > component_to_base_index (const unsigned int component) const
std::pair< unsigned int, unsigned int > block_to_base_index (const unsigned int block) const
std::pair< unsigned int, types::global_dof_index > system_to_block_index (const unsigned int component) const
unsigned int component_to_block_index (const unsigned int component) const
ComponentMask component_mask (const FEValuesExtractors::Scalar &scalar) const
ComponentMask component_mask (const FEValuesExtractors::Vector &vector) const
ComponentMask component_mask (const FEValuesExtractors::SymmetricTensor< 2 > &sym_tensor) const
ComponentMask component_mask (const BlockMask &block_mask) const
BlockMask block_mask (const FEValuesExtractors::Scalar &scalar) const
BlockMask block_mask (const FEValuesExtractors::Vector &vector) const
BlockMask block_mask (const FEValuesExtractors::SymmetricTensor< 2 > &sym_tensor) const
BlockMask block_mask (const ComponentMask &component_mask) const
const std::vector< Point< dim > > & get_unit_support_points () const
bool has_support_points () const
const std::vector< Point< dim - 1 > > & get_unit_face_support_points (const unsigned int face_no=0) const
bool has_face_support_points (const unsigned int face_no=0) const
const std::vector< Point< dim > > & get_generalized_support_points () const
bool has_generalized_support_points () const
GeometryPrimitive get_associated_geometry_primitive (const unsigned int cell_dof_index) const
void subscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
void unsubscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
unsigned int n_subscriptions () const
void list_subscribers (StreamType &stream) const
void list_subscribers () const
bool prolongation_is_implemented () const
bool isotropic_prolongation_is_implemented () const
bool restriction_is_implemented () const
bool isotropic_restriction_is_implemented () const
bool restriction_is_additive (const unsigned int index) const
const FullMatrix< double > & constraints (const ::internal::SubfaceCase< dim > &subface_case=::internal::SubfaceCase< dim >::case_isotropic) const
bool constraints_are_implemented (const ::internal::SubfaceCase< dim > &subface_case=::internal::SubfaceCase< dim >::case_isotropic) const
std::pair< unsigned int, unsigned int > system_to_component_index (const unsigned int index) const
unsigned int component_to_system_index (const unsigned int component, const unsigned int index) const
std::pair< unsigned int, unsigned int > face_system_to_component_index (const unsigned int index, const unsigned int face_no=0) const
unsigned int adjust_quad_dof_index_for_face_orientation (const unsigned int index, const unsigned int face_no, const unsigned char combined_orientation) const
unsigned int adjust_line_dof_index_for_line_orientation (const unsigned int index, const unsigned char combined_orientation) const
const ComponentMask & get_nonzero_components (const unsigned int i) const
unsigned int n_nonzero_components (const unsigned int i) const
bool is_primitive () const
bool is_primitive (const unsigned int i) const
unsigned int n_base_elements () const
unsigned int element_multiplicity (const unsigned int index) const
const FiniteElement< dim, spacedim > & get_sub_fe (const ComponentMask &mask) const
std::pair< std::pair< unsigned int, unsigned int >, unsigned int > system_to_base_index (const unsigned int index) const
std::pair< std::pair< unsigned int, unsigned int >, unsigned int > face_system_to_base_index (const unsigned int index, const unsigned int face_no=0) const
types::global_dof_index first_block_of_base (const unsigned int b) const
std::pair< unsigned int, unsigned int > component_to_base_index (const unsigned int component) const
std::pair< unsigned int, unsigned int > block_to_base_index (const unsigned int block) const
std::pair< unsigned int, types::global_dof_index > system_to_block_index (const unsigned int component) const
unsigned int component_to_block_index (const unsigned int component) const
ComponentMask component_mask (const FEValuesExtractors::Scalar &scalar) const
ComponentMask component_mask (const FEValuesExtractors::Vector &vector) const
ComponentMask component_mask (const FEValuesExtractors::SymmetricTensor< 2 > &sym_tensor) const
ComponentMask component_mask (const BlockMask &block_mask) const
BlockMask block_mask (const FEValuesExtractors::Scalar &scalar) const
BlockMask block_mask (const FEValuesExtractors::Vector &vector) const
BlockMask block_mask (const FEValuesExtractors::SymmetricTensor< 2 > &sym_tensor) const
BlockMask block_mask (const ComponentMask &component_mask) const
const std::vector< Point< dim > > & get_unit_support_points () const
bool has_support_points () const
const std::vector< Point< dim - 1 > > & get_unit_face_support_points (const unsigned int face_no=0) const
bool has_face_support_points (const unsigned int face_no=0) const
const std::vector< Point< dim > > & get_generalized_support_points () const
bool has_generalized_support_points () const
GeometryPrimitive get_associated_geometry_primitive (const unsigned int cell_dof_index) const
void subscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
void unsubscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
unsigned int n_subscriptions () const
void list_subscribers (StreamType &stream) const
void list_subscribers () const
Public Member Functions inherited from Subscriptor
Subscriptor ()
Subscriptor (const Subscriptor &)
Subscriptor (Subscriptor &&) noexcept
virtual ~Subscriptor ()
Subscriptor & operator= (const Subscriptor &)
Subscriptor & operator= (Subscriptor &&) noexcept
void serialize (Archive &ar, const unsigned int version)
void subscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
void unsubscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
unsigned int n_subscriptions () const
void list_subscribers (StreamType &stream) const
void list_subscribers () const
void subscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
void unsubscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
unsigned int n_subscriptions () const
void list_subscribers (StreamType &stream) const
void list_subscribers () const
Public Member Functions inherited from FiniteElementData< int dim >
FiniteElementData (const std::vector< unsigned int > &dofs_per_object, const unsigned int n_components, const unsigned int degree, const Conformity conformity=unknown, const BlockIndices &block_indices=BlockIndices())
FiniteElementData (const std::vector< unsigned int > &dofs_per_object, const ReferenceCell reference_cell, const unsigned int n_components, const unsigned int degree, const Conformity conformity=unknown, const BlockIndices &block_indices=BlockIndices())
FiniteElementData (const internal::GenericDoFsPerObject &data, const ReferenceCell reference_cell, const unsigned int n_components, const unsigned int degree, const Conformity conformity=unknown, const BlockIndices &block_indices=BlockIndices())
ReferenceCell reference_cell () const
unsigned int n_unique_2d_subobjects () const
unsigned int n_unique_faces () const
unsigned int n_dofs_per_vertex () const
unsigned int n_dofs_per_line () const
unsigned int n_dofs_per_quad (unsigned int face_no=0) const
unsigned int max_dofs_per_quad () const
unsigned int n_dofs_per_hex () const
unsigned int n_dofs_per_face (unsigned int face_no=0, unsigned int child=0) const
unsigned int max_dofs_per_face () const
unsigned int n_dofs_per_cell () const
unsigned int n_dofs_per_object (const unsigned int i=0) const
unsigned int n_components () const
unsigned int n_blocks () const
const BlockIndices & block_indices () const
unsigned int tensor_degree () const
bool conforms (const Conformity) const
bool operator== (const FiniteElementData &) const
unsigned int get_first_line_index () const
unsigned int get_first_quad_index (const unsigned int quad_no=0) const
unsigned int get_first_hex_index () const
unsigned int get_first_face_line_index (const unsigned int face_no=0) const
unsigned int get_first_face_quad_index (const unsigned int face_no=0) const
Static Private Member Functions
static std::vector< unsigned int > get_dpo_vector (const unsigned int degree)
Additional Inherited Members
Public Types inherited from FE_Poly< dim, dim >
enum Conformity
Public Types inherited from FiniteElement< int dim, int spacedim >
enum Conformity
Public Types inherited from FiniteElementData< int dim >
enum Conformity
Static Public Member Functions inherited from FE_Poly< dim, dim >
static ::ExceptionBase & ExcShapeFunctionNotPrimitive (int arg1)
static ::ExceptionBase & ExcFENotPrimitive ()
static ::ExceptionBase & ExcUnitShapeValuesDoNotExist ()
static ::ExceptionBase & ExcFEHasNoSupportPoints ()
static ::ExceptionBase & ExcEmbeddingVoid ()
static ::ExceptionBase & ExcProjectionVoid ()
static ::ExceptionBase & ExcWrongInterfaceMatrixSize (int arg1, int arg2)
static ::ExceptionBase & ExcInterpolationNotImplemented ()
static ::ExceptionBase & ExcInUse (int arg1, std::string arg2, std::string arg3)
static ::ExceptionBase & ExcNoSubscriber (std::string arg1, std::string arg2)
Static Public Member Functions inherited from FiniteElement< int dim, int spacedim >
static ::ExceptionBase & ExcShapeFunctionNotPrimitive (int arg1)
static ::ExceptionBase & ExcFENotPrimitive ()
static ::ExceptionBase & ExcUnitShapeValuesDoNotExist ()
static ::ExceptionBase & ExcFEHasNoSupportPoints ()
static ::ExceptionBase & ExcEmbeddingVoid ()
static ::ExceptionBase & ExcProjectionVoid ()
static ::ExceptionBase & ExcWrongInterfaceMatrixSize (int arg1, int arg2)
static ::ExceptionBase & ExcInterpolationNotImplemented ()
static ::ExceptionBase & ExcInUse (int arg1, std::string arg2, std::string arg3)
static ::ExceptionBase & ExcNoSubscriber (std::string arg1, std::string arg2)
Static Public Member Functions inherited from Subscriptor
static ::ExceptionBase & ExcInUse (int arg1, std::string arg2, std::string arg3)
static ::ExceptionBase & ExcNoSubscriber (std::string arg1, std::string arg2)
Public Attributes inherited from FE_Poly< dim, dim >
unknown
L2
Hcurl
Hdiv
H1
H2
const unsigned int dofs_per_vertex
const unsigned int dofs_per_line
const unsigned int dofs_per_quad
const unsigned int dofs_per_hex
const unsigned int first_line_index
const unsigned int first_quad_index
const unsigned int first_hex_index
const unsigned int first_face_line_index
const unsigned int first_face_quad_index
const unsigned int dofs_per_face
const unsigned int dofs_per_cell
const unsigned int components
const unsigned int degree
const Conformity conforming_space
const BlockIndices block_indices_data
Public Attributes inherited from FiniteElement< int dim, int spacedim >
unknown
L2
Hcurl
Hdiv
H1
H2
const unsigned int dofs_per_vertex
const unsigned int dofs_per_line
const unsigned int dofs_per_quad
const unsigned int dofs_per_hex
const unsigned int first_line_index
const unsigned int first_quad_index
const unsigned int first_hex_index
const unsigned int first_face_line_index
const unsigned int first_face_quad_index
const unsigned int dofs_per_face
const unsigned int dofs_per_cell
const unsigned int components
const unsigned int degree
const Conformity conforming_space
const BlockIndices block_indices_data
Public Attributes inherited from FiniteElementData< int dim >
unknown
L2
Hcurl
Hdiv
H1
H2
const unsigned int dofs_per_vertex
const unsigned int dofs_per_line
const unsigned int dofs_per_quad
const unsigned int dofs_per_hex
const unsigned int first_line_index
const unsigned int first_quad_index
const unsigned int first_hex_index
const unsigned int first_face_line_index
const unsigned int first_face_quad_index
const unsigned int dofs_per_face
const unsigned int dofs_per_cell
const unsigned int components
const unsigned int degree
const Conformity conforming_space
const BlockIndices block_indices_data
Static Public Attributes inherited from FE_Poly< dim, dim >
static constexpr unsigned int space_dimension
static constexpr unsigned int dimension
Static Public Attributes inherited from FiniteElement< int dim, int spacedim >
static constexpr unsigned int space_dimension
static constexpr unsigned int dimension
Static Public Attributes inherited from FiniteElementData< int dim >
static constexpr unsigned int dimension
Protected Member Functions inherited from FE_Poly< dim, dim >
virtual std::unique_ptr< typename FiniteElement< dim, spacedim >::InternalDataBase > get_data (const UpdateFlags update_flags, const Mapping< dim, spacedim > &mapping, const Quadrature< dim > &quadrature, ::internal::FEValuesImplementation::FiniteElementRelatedData< dim, spacedim > &output_data) const override
virtual void fill_fe_values (const typename Triangulation< dim, spacedim >::cell_iterator &cell, const CellSimilarity::Similarity cell_similarity, const Quadrature< dim > &quadrature, const Mapping< dim, spacedim > &mapping, const typename Mapping< dim, spacedim >::InternalDataBase &mapping_internal, const internal::FEValuesImplementation::MappingRelatedData< dim, spacedim > &mapping_data, const typename FiniteElement< dim, spacedim >::InternalDataBase &fe_internal, ::internal::FEValuesImplementation::FiniteElementRelatedData< dim, spacedim > &output_data) const override
virtual void fill_fe_values (const typename Triangulation< dim, spacedim >::cell_iterator &cell, const CellSimilarity::Similarity cell_similarity, const Quadrature< dim > &quadrature, const Mapping< dim, spacedim > &mapping, const typename Mapping< dim, spacedim >::InternalDataBase &mapping_internal, const internal::FEValuesImplementation::MappingRelatedData< dim, spacedim > &mapping_data, const InternalDataBase &fe_internal, ::internal::FEValuesImplementation::FiniteElementRelatedData< dim, spacedim > &output_data) const =0
virtual void fill_fe_face_values (const typename Triangulation< dim, spacedim >::cell_iterator &cell, const unsigned int face_no, const hp::QCollection< dim - 1 > &quadrature, const Mapping< dim, spacedim > &mapping, const typename Mapping< dim, spacedim >::InternalDataBase &mapping_internal, const internal::FEValuesImplementation::MappingRelatedData< dim, spacedim > &mapping_data, const typename FiniteElement< dim, spacedim >::InternalDataBase &fe_internal, ::internal::FEValuesImplementation::FiniteElementRelatedData< dim, spacedim > &output_data) const override
virtual void fill_fe_face_values (const typename Triangulation< dim, spacedim >::cell_iterator &cell, const unsigned int face_no, const hp::QCollection< dim - 1 > &quadrature, const Mapping< dim, spacedim > &mapping, const typename Mapping< dim, spacedim >::InternalDataBase &mapping_internal, const internal::FEValuesImplementation::MappingRelatedData< dim, spacedim > &mapping_data, const InternalDataBase &fe_internal, ::internal::FEValuesImplementation::FiniteElementRelatedData< dim, spacedim > &output_data) const
virtual void fill_fe_face_values (const typename Triangulation< dim, spacedim >::cell_iterator &cell, const unsigned int face_no, const Quadrature< dim - 1 > &quadrature, const Mapping< dim, spacedim > &mapping, const typename Mapping< dim, spacedim >::InternalDataBase &mapping_internal, const internal::FEValuesImplementation::MappingRelatedData< dim, spacedim > &mapping_data, const InternalDataBase &fe_internal, internal::FEValuesImplementation::FiniteElementRelatedData< dim, spacedim > &output_data) const
virtual void fill_fe_subface_values (const typename Triangulation< dim, spacedim >::cell_iterator &cell, const unsigned int face_no, const unsigned int sub_no, const Quadrature< dim - 1 > &quadrature, const Mapping< dim, spacedim > &mapping, const typename Mapping< dim, spacedim >::InternalDataBase &mapping_internal, const internal::FEValuesImplementation::MappingRelatedData< dim, spacedim > &mapping_data, const typename FiniteElement< dim, spacedim >::InternalDataBase &fe_internal, ::internal::FEValuesImplementation::FiniteElementRelatedData< dim, spacedim > &output_data) const override
virtual void fill_fe_subface_values (const typename Triangulation< dim, spacedim >::cell_iterator &cell, const unsigned int face_no, const unsigned int sub_no, const Quadrature< dim - 1 > &quadrature, const Mapping< dim, spacedim > &mapping, const typename Mapping< dim, spacedim >::InternalDataBase &mapping_internal, const internal::FEValuesImplementation::MappingRelatedData< dim, spacedim > &mapping_data, const InternalDataBase &fe_internal, ::internal::FEValuesImplementation::FiniteElementRelatedData< dim, spacedim > &output_data) const =0
void correct_hessians (internal::FEValuesImplementation::FiniteElementRelatedData< dim, spacedim > &output_data, const internal::FEValuesImplementation::MappingRelatedData< dim, spacedim > &mapping_data, const unsigned int n_q_points) const
void correct_third_derivatives (internal::FEValuesImplementation::FiniteElementRelatedData< dim, spacedim > &output_data, const internal::FEValuesImplementation::MappingRelatedData< dim, spacedim > &mapping_data, const unsigned int n_q_points) const
void reinit_restriction_and_prolongation_matrices (const bool isotropic_restriction_only=false, const bool isotropic_prolongation_only=false)
TableIndices< 2 > interface_constraints_size () const
virtual std::unique_ptr< InternalDataBase > get_face_data (const UpdateFlags update_flags, const Mapping< dim, spacedim > &mapping, const hp::QCollection< dim - 1 > &quadrature, ::internal::FEValuesImplementation::FiniteElementRelatedData< dim, spacedim > &output_data) const
virtual std::unique_ptr< InternalDataBase > get_face_data (const UpdateFlags update_flags, const Mapping< dim, spacedim > &mapping, const Quadrature< dim - 1 > &quadrature, internal::FEValuesImplementation::FiniteElementRelatedData< dim, spacedim > &output_data) const
virtual std::unique_ptr< InternalDataBase > get_subface_data (const UpdateFlags update_flags, const Mapping< dim, spacedim > &mapping, const Quadrature< dim - 1 > &quadrature, ::internal::FEValuesImplementation::FiniteElementRelatedData< dim, spacedim > &output_data) const
Protected Member Functions inherited from FiniteElement< int dim, int spacedim >
void reinit_restriction_and_prolongation_matrices (const bool isotropic_restriction_only=false, const bool isotropic_prolongation_only=false)
TableIndices< 2 > interface_constraints_size () const
Static Protected Member Functions inherited from FE_Poly< dim, dim >
static std::vector< unsigned int > compute_n_nonzero_components (const std::vector< ComponentMask > &nonzero_components)
Static Protected Member Functions inherited from FiniteElement< int dim, int spacedim >
static std::vector< unsigned int > compute_n_nonzero_components (const std::vector< ComponentMask > &nonzero_components)
Protected Attributes inherited from FE_Poly< dim, dim >
const std::unique_ptr< ScalarPolynomialsBase< dim > > poly_space
std::vector< std::vector< FullMatrix< double > > > restriction
std::vector< std::vector< FullMatrix< double > > > prolongation
FullMatrix< double > interface_constraints
std::vector< Point< dim > > unit_support_points
std::vector< std::vector< Point< dim - 1 > > > unit_face_support_points
std::vector< Point< dim > > generalized_support_points
std::vector< std::vector< Point< dim - 1 > > > generalized_face_support_points
std::vector< Table< 2, int > > adjust_quad_dof_index_for_face_orientation_table
std::vector< int > adjust_line_dof_index_for_line_orientation_table
std::vector< std::pair< unsigned int, unsigned int > > system_to_component_table
std::vector< std::vector< std::pair< unsigned int, unsigned int > > > face_system_to_component_table
std::vector< std::pair< std::pair< unsigned int, unsigned int >, unsigned int > > system_to_base_table
std::vector< std::vector< std::pair< std::pair< unsigned int, unsigned int >, unsigned int > > > face_system_to_base_table
BlockIndices base_to_block_indices
std::vector< std::pair< std::pair< unsigned int, unsigned int >, unsigned int > > component_to_base_table
const std::vector< bool > restriction_is_additive_flags
const std::vector< ComponentMask > nonzero_components
const std::vector< unsigned int > n_nonzero_components_table
const bool cached_primitivity
Protected Attributes inherited from FiniteElement< int dim, int spacedim >
std::vector< std::vector< FullMatrix< double > > > restriction
std::vector< std::vector< FullMatrix< double > > > prolongation
FullMatrix< double > interface_constraints
std::vector< Point< dim > > unit_support_points
std::vector< std::vector< Point< dim - 1 > > > unit_face_support_points
std::vector< Point< dim > > generalized_support_points
std::vector< std::vector< Point< dim - 1 > > > generalized_face_support_points
std::vector< Table< 2, int > > adjust_quad_dof_index_for_face_orientation_table
std::vector< int > adjust_line_dof_index_for_line_orientation_table
std::vector< std::pair< unsigned int, unsigned int > > system_to_component_table
std::vector< std::vector< std::pair< unsigned int, unsigned int > > > face_system_to_component_table
std::vector< std::pair< std::pair< unsigned int, unsigned int >, unsigned int > > system_to_base_table
std::vector< std::vector< std::pair< std::pair< unsigned int, unsigned int >, unsigned int > > > face_system_to_base_table
BlockIndices base_to_block_indices
std::vector< std::pair< std::pair< unsigned int, unsigned int >, unsigned int > > component_to_base_table
const std::vector< bool > restriction_is_additive_flags
const std::vector< ComponentMask > nonzero_components
const std::vector< unsigned int > n_nonzero_components_table
const bool cached_primitivity
Detailed Description
template<int dim, int spacedim = dim>
class FE_AggloDGP< dim, spacedim >
$. Since the DGP space has only three unknowns for each quadrilateral, it is immediately clear that this element can not be continuous.
The basis functions used in this element for the space described above are chosen to form a Legendre basis on the unit square, i.e., in particular they are $L_2$-orthogonal and normalized on the reference cell (but not necessarily on the real cell). As a consequence, the first basis function of this element is always the function that is constant and equal to one, regardless of the polynomial degree of the element. In addition, as a result of the orthogonality of the basis functions, the mass matrix is diagonal if the grid cells are parallelograms. Note that this is in contrast to the FE_DGPMonomial class that actually uses the monomial basis listed above as basis functions, without transformation from reference to real cell.
The shape functions are defined in the class PolynomialSpace. The polynomials used inside PolynomialSpace are Polynomials::Legendre up to degree p given in FE_AggloDGP. For the ordering of the basis functions, refer to PolynomialSpace, remembering that the Legendre polynomials are ordered by ascending degree.
Note
This element is not defined by finding shape functions within the given function space that interpolate a particular set of points. Consequently, there are no support points to which a given function could be interpolated; finding a finite element function that approximates a given function is therefore only possible through projection, rather than interpolation. Secondly, the shape functions of this element do not jointly add up to one. As a consequence of this, adding or subtracting a constant value – such as one would do to make a function have mean value zero – can not be done by simply subtracting the constant value from each degree of freedom. Rather, one needs to use the fact that the first basis function is constant equal to one and simply subtract the constant from the value of the degree of freedom corresponding to this first shape function on each cell.
This class is only partially implemented for the codimension one case (spacedim != dim), since no passage of information between meshes of different refinement level is possible because the embedding and projection matrices are not computed in the class constructor.
Transformation properties
It is worth noting that under a (bi-, tri-)linear mapping, the space described by this element does not contain $P(k)$, even if we use a basis of polynomials of degree $k$. Consequently, for example, on meshes with non-affine cells, a linear function can not be exactly represented by elements of type FE_AggloDGP(1) or FE_DGPMonomial(1).
This can be understood by the following 2-d example: consider the cell with vertices at $(0,0),(1,0),(0,1),(s,s)$:
For this cell, a bilinear transformation $F$ produces the relations $x=\hat x+\hat x\hat y$ and $y=\hat y+\hat x\hat y$ that correlate reference coordinates $\hat x,\hat y$ and coordinates in real space $x,y$. Under this mapping, the constant function is clearly mapped onto itself, but the two other shape functions of the $P_1$ space, namely $\phi_1(\hat x,\hat y)=\hat x$ and $\phi_2(\hat x,\hat y)=\hat y$ are mapped onto $\phi_1(x,y)=\frac{x-t}{t(s-1)},\phi_2(x,y)=t$ where $t=\frac{y}{s-x+sx+y-sy}$.
For the simple case that $s=1$, i.e. if the real cell is the unit square, the expressions can be simplified to $t=y$ and $\phi_1(x,y)=x,\phi_2(x,y)=y$. However, for all other cases, the functions $\phi_1(x,y),\phi_2(x,y)$ are not linear any more, and neither is any linear combination of them. Consequently, the linear functions are not within the range of the mapped $P_1$ polynomials.
Visualization of shape functions
In 2d, the shape functions of this element look as follows.
$P_0$ element
$P_0$ element, shape function 0
$P_1$ element
$P_1$ element, shape function 0
$P_1$ element, shape function 1
$P_1$ element, shape function 2
$P_2$ element
$P_2$ element, shape function 0
$P_2$ element, shape function 1
$P_2$ element, shape function 2
$P_2$ element, shape function 3
$P_2$ element, shape function 4
$P_2$ element, shape function 5
$P_3$ element
$P_3$ element, shape function 0
$P_3$ element, shape function 1
$P_3$ element, shape function 2
$P_3$ element, shape function 3
$P_3$ element, shape function 4
$P_3$ element, shape function 5
$P_3$ element, shape function 6
$P_3$ element, shape function 7
$P_3$ element, shape function 8
$P_3$ element, shape function 9
$P_4$ element
$P_4$ element, shape function 0
$P_4$ element, shape function 1
$P_4$ element, shape function 2
$P_4$ element, shape function 3
$P_4$ element, shape function 4
$P_4$ element, shape function 5
$P_4$ element, shape function 6
$P_4$ element, shape function 7
$P_4$ element, shape function 8
$P_4$ element, shape function 9
$P_4$ element, shape function 10
$P_4$ element, shape function 11
$P_4$ element, shape function 12
$P_4$ element, shape function 13
$P_4$ element, shape function 14
Definition at line 311 of file fe_agglodgp.h.
Constructor & Destructor Documentation
FE_AggloDGP()
template<int dim, int spacedim> DEAL_II_NAMESPACE_OPEN FE_AggloDGP< dim, spacedim >::FE_AggloDGP (const unsigned int p)
Constructor for tensor product polynomials of degree p.
Definition at line 28 of file fe_agglodgp.cc.
References FETools::compute_embedding_matrices(), FETools::compute_projection_matrices(), FE_Poly< dim, dim >::prolongation, FE_Poly< dim, dim >::reinit_restriction_and_prolongation_matrices(), and FE_Poly< dim, dim >::restriction.
Member Function Documentation
clone()
template<int dim, int spacedim> std::unique_ptr< FiniteElement< dim, spacedim > > FE_AggloDGP< dim, spacedim >::clone () const override virtual
Implements FE_Poly< dim, dim >.
Definition at line 77 of file fe_agglodgp.cc.
compare_for_domination()
template<int dim, int spacedim> FiniteElementDomination::Domination FE_AggloDGP< dim, spacedim >::compare_for_domination (const FiniteElement< dim, spacedim > & fe_other, const unsigned int codim = 0) const final override virtual
Reimplemented from FE_Poly< dim, dim >.
Definition at line 215 of file fe_agglodgp.cc.
References Assert, DEAL_II_NOT_IMPLEMENTED, FiniteElementDomination::either_element_can_dominate, FiniteElementDomination::neither_element_dominates, FiniteElementDomination::no_requirements, FiniteElementDomination::other_element_dominates, and FiniteElementDomination::this_element_dominates.
get_constant_modes()
template<int dim, int spacedim> std::pair< Table< 2, bool >, std::vector< unsigned int > > FE_AggloDGP< dim, spacedim >::get_constant_modes () const override virtual
Return a list of constant modes of the element. For this element, the first entry is true, all other are false.
Reimplemented from FE_Poly< dim, dim >.
Definition at line 272 of file fe_agglodgp.cc.
get_dpo_vector()
template<int dim, int spacedim> std::vector< unsigned int > FE_AggloDGP< dim, spacedim >::get_dpo_vector (const unsigned int degree) static private
Only for internal use. Its full name is get_dofs_per_object_vector function and it creates the dofs_per_object vector that is needed within the constructor to be passed to the constructor of FiniteElementData.
Definition at line 91 of file fe_agglodgp.cc.
get_face_interpolation_matrix()
template<int dim, int spacedim> void FE_AggloDGP< dim, spacedim >::get_face_interpolation_matrix (const FiniteElement< dim, spacedim > & source, FullMatrix< double > & matrix, const unsigned int face_no = 0) const override virtual
Return the matrix interpolating from a face of one element to the face of the neighboring element. The size of the matrix is then source.dofs_per_face times this->dofs_per_face.
Derived elements will have to implement this function. They may only provide interpolation matrices for certain source finite elements, for example those from the same family. If they don't implement interpolation from a given element, then they must throw an exception of type FiniteElement<dim,spacedim>::ExcInterpolationNotImplemented.
Reimplemented from FE_Poly< dim, dim >.
Definition at line 107 of file fe_agglodgp.cc.
References Assert, AssertThrow, FiniteElement< int dim, int spacedim >::get_name(), FullMatrix< typename number >::m(), and FullMatrix< typename number >::n().
get_name()
template<int dim, int spacedim> std::string FE_AggloDGP< dim, spacedim >::get_name () const override virtual
Return a string that uniquely identifies a finite element. This class returns FE_AggloDGP<dim>(degree), with dim and degree replaced by appropriate values.
Implements FE_Poly< dim, dim >.
Definition at line 60 of file fe_agglodgp.cc.
References Utilities::dim_string().
get_subface_interpolation_matrix()
template<int dim, int spacedim> void FE_AggloDGP< dim, spacedim >::get_subface_interpolation_matrix (const FiniteElement< dim, spacedim > & source, const unsigned int subface, FullMatrix< double > & matrix, const unsigned int face_no = 0) const override virtual
Return the matrix interpolating from a face of one element to the face of the neighboring element. The size of the matrix is then source.dofs_per_face times this->dofs_per_face.
Derived elements will have to implement this function. They may only provide interpolation matrices for certain source finite elements, for example those from the same family. If they don't implement interpolation from a given element, then they must throw an exception of type FiniteElement<dim,spacedim>::ExcInterpolationNotImplemented.
Reimplemented from FE_Poly< dim, dim >.
Definition at line 133 of file fe_agglodgp.cc.
References Assert, AssertThrow, FiniteElement< int dim, int spacedim >::get_name(), FullMatrix< typename number >::m(), and FullMatrix< typename number >::n().
has_support_on_face()
template<int dim, int spacedim> bool FE_AggloDGP< dim, spacedim >::has_support_on_face (const unsigned int shape_index, const unsigned int face_index) const override virtual
This function returns true, if the shape function shape_index has non-zero function values somewhere on the face face_index.
Reimplemented from FE_Poly< dim, dim >.
Definition at line 261 of file fe_agglodgp.cc.
hp_constraints_are_implemented()
template<int dim, int spacedim> bool FE_AggloDGP< dim, spacedim >::hp_constraints_are_implemented () const override virtual
Return whether this element implements its hanging node constraints in the new way, which has to be used to make elements "hp-compatible".
For the FE_AggloDGP class the result is always true (independent of the degree of the element), as it has no hanging nodes (being a discontinuous element).
Reimplemented from FE_Poly< dim, dim >.
Definition at line 160 of file fe_agglodgp.cc.
hp_line_dof_identities()
template<int dim, int spacedim> std::vector< std::pair< unsigned int, unsigned int > > FE_AggloDGP< dim, spacedim >::hp_line_dof_identities (const FiniteElement< dim, spacedim > & fe_other) const override virtual
Same as hp_vertex_dof_indices(), except that the function treats degrees of freedom on lines.
This being a discontinuous element, the set of such constraints is of course empty.
Reimplemented from FE_Poly< dim, dim >.
Definition at line 180 of file fe_agglodgp.cc.
References DEAL_II_NOT_IMPLEMENTED.
hp_quad_dof_identities()
template<int dim, int spacedim> std::vector< std::pair< unsigned int, unsigned int > > FE_AggloDGP< dim, spacedim >::hp_quad_dof_identities (const FiniteElement< dim, spacedim > & fe_other, const unsigned int face_no = 0) const override virtual
Same as hp_vertex_dof_indices(), except that the function treats degrees of freedom on quads.
This being a discontinuous element, the set of such constraints is of course empty.
Reimplemented from FE_Poly< dim, dim >.
Definition at line 197 of file fe_agglodgp.cc.
References DEAL_II_NOT_IMPLEMENTED.
hp_vertex_dof_identities()
template<int dim, int spacedim> std::vector< std::pair< unsigned int, unsigned int > > FE_AggloDGP< dim, spacedim >::hp_vertex_dof_identities (const FiniteElement< dim, spacedim > & fe_other) const override virtual
If, on a vertex, several finite elements are active, the hp-code first assigns the degrees of freedom of each of these FEs different global indices. It then calls this function to find out which of them should get identical values, and consequently can receive the same global DoF index. This function therefore returns a list of identities between DoFs of the present finite element object with the DoFs of fe_other, which is a reference to a finite element object representing one of the other finite elements active on this particular vertex. The function computes which of the degrees of freedom of the two finite element objects are equivalent, both numbered between zero and the corresponding value of n_dofs_per_vertex() of the two finite elements. The first index of each pair denotes one of the vertex dofs of the present element, whereas the second is the corresponding index of the other finite element.
This being a discontinuous element, the set of such constraints is of course empty.
Reimplemented from FE_Poly< dim, dim >.
Definition at line 169 of file fe_agglodgp.cc.
memory_consumption()
template<int dim, int spacedim> std::size_t FE_AggloDGP< dim, spacedim >::memory_consumption () const override virtual
Determine an estimate for the memory consumption (in bytes) of this object.
This function is made virtual, since finite element objects are usually accessed through pointers to their base class, rather than the class itself.
Reimplemented from FE_Poly< dim, dim >.
Definition at line 284 of file fe_agglodgp.cc.
References DEAL_II_NOT_IMPLEMENTED.
The documentation for this class was generated from the following files:
/github/workspace/include/fe_agglodgp.h
/github/workspace/source/fe_agglodgp.cc