PolyDEAL: Poisson< dim > Class Template Reference
Poisson< dim > Class Template Reference
Public Member Functions
Poisson ()
void run ()
Poisson ()
void run ()
Public Attributes
double penalty = 3.
Private Member Functions
void make_grid ()
void setup_agglomeration ()
void distribute_jumps_and_averages (FEFaceValues< dim > &fe_face, FEFaceValues< dim > &fe_face1, const typename DoFHandler< dim >::active_cell_iterator &cell, const unsigned int f)
void assemble_system ()
void solve ()
void output_results ()
void make_grid ()
void distribute_jumps_and_averages (FEFaceValues< dim > &fe_face0, FEFaceValues< dim > &fe_face1, const typename DoFHandler< dim >::active_cell_iterator &cell, const unsigned int f)
void assemble_system ()
void solve ()
void output_results ()
Private Attributes
Triangulation< dim > tria
MappingQ< dim > mapping
FE_DGQ< dim > dg_fe
DoFHandler< dim > classical_dh
std::unique_ptr< AgglomerationHandler< dim > > ah
SparsityPattern sparsity
SparseMatrix< double > system_matrix
Vector< double > solution
Vector< double > system_rhs
std::unique_ptr< GridTools::Cache< dim > > cached_tria
std::unique_ptr< const Function< dim > > rhs_function
Detailed Description
template<int dim>
class Poisson< dim >
Definition at line 44 of file assembly_check.cc.
Constructor & Destructor Documentation
Poisson() [1/2]
template<int dim> Poisson< dim >::Poisson ()
Definition at line 88 of file assembly_check.cc.
References mapping.
Poisson() [2/2]
template<int dim> Poisson< dim >::Poisson ()
Member Function Documentation
assemble_system() [1/2]
template<int dim> void Poisson< dim >::assemble_system () private
Definition at line 328 of file assembly_check.cc.
References FEValues< int dim, int spacedim >::get_quadrature_points(), FEValues< int dim, int spacedim >::JxW(), DoFTools::make_flux_sparsity_pattern(), mapping, FEValues< int dim, int spacedim >::quadrature_point_indices(), FEValues< int dim, int spacedim >::reinit(), FEValues< int dim, int spacedim >::shape_grad(), FEValues< int dim, int spacedim >::shape_value(), update_gradients, update_JxW_values, update_normal_vectors, update_quadrature_points, and update_values.
assemble_system() [2/2]
template<int dim> void Poisson< dim >::assemble_system () private
distribute_jumps_and_averages() [1/2]
template<int dim> void Poisson< dim >::distribute_jumps_and_averages (FEFaceValues< dim > & fe_face, FEFaceValues< dim > & fe_face1, const typename DoFHandler< dim >::active_cell_iterator & cell, const unsigned int f) private
Definition at line 176 of file assembly_check.cc.
References FEFaceValues< int dim, int spacedim >::dofs_per_cell, FEFaceValues< int dim, int spacedim >::get_normal_vectors(), FEFaceValues< int dim, int spacedim >::JxW(), FEFaceValues< int dim, int spacedim >::quadrature_point_indices(), FEFaceValues< int dim, int spacedim >::reinit(), FEFaceValues< int dim, int spacedim >::shape_grad(), and FEFaceValues< int dim, int spacedim >::shape_value().
distribute_jumps_and_averages() [2/2]
template<int dim> void Poisson< dim >::distribute_jumps_and_averages (FEFaceValues< dim > & fe_face0, FEFaceValues< dim > & fe_face1, const typename DoFHandler< dim >::active_cell_iterator & cell, const unsigned int f) private
make_grid() [1/2]
template<int dim> void Poisson< dim >::make_grid () private
Definition at line 96 of file assembly_check.cc.
References GridGenerator::hyper_cube(), mapping, and Triangulation< int dim, int spacedim >::refine_global().
make_grid() [2/2]
template<int dim> void Poisson< dim >::make_grid () private
output_results() [1/2]
template<int dim> void Poisson< dim >::output_results () private
Definition at line 638 of file assembly_check.cc.
References DataOut< int dim, int spacedim >::add_data_vector(), DataOut< int dim, int spacedim >::attach_dof_handler(), DataOut< int dim, int spacedim >::build_patches(), mapping, and DataOut< int dim, int spacedim >::write_vtu().
output_results() [2/2]
template<int dim> void Poisson< dim >::output_results () private
run() [1/2]
template<int dim> void Poisson< dim >::run ()
Definition at line 653 of file assembly_check.cc.
Referenced by main().
run() [2/2]
template<int dim> void Poisson< dim >::run ()
setup_agglomeration()
template<int dim> void Poisson< dim >::setup_agglomeration () private
Definition at line 110 of file assembly_check.cc.
References GridOut::write_vtk().
solve() [1/2]
template<int dim> void Poisson< dim >::solve () private
Definition at line 627 of file assembly_check.cc.
References SparseDirectUMFPACK::initialize(), and SparseDirectUMFPACK::vmult().
solve() [2/2]
template<int dim> void Poisson< dim >::solve () private
Member Data Documentation
ah
template<int dim> std::unique_ptr<AgglomerationHandler<dim> > Poisson< dim >::ah private
Definition at line 69 of file assembly_check.cc.
cached_tria
template<int dim> std::unique_ptr<GridTools::Cache<dim> > Poisson< dim >::cached_tria private
Definition at line 74 of file assembly_check.cc.
classical_dh
template<int dim> DoFHandler< dim > Poisson< dim >::classical_dh private
Definition at line 68 of file assembly_check.cc.
dg_fe
template<int dim> FE_DGQ< dim > Poisson< dim >::dg_fe private
Definition at line 67 of file assembly_check.cc.
mapping
template<int dim> MappingQ< dim > Poisson< dim >::mapping private
Definition at line 66 of file assembly_check.cc.
penalty
template<int dim> double Poisson< dim >::penalty = 3.
Definition at line 82 of file assembly_check.cc.
rhs_function
template<int dim> std::unique_ptr< const Function< dim > > Poisson< dim >::rhs_function private
Definition at line 75 of file assembly_check.cc.
solution
template<int dim> Vector< double > Poisson< dim >::solution private
Definition at line 72 of file assembly_check.cc.
sparsity
template<int dim> SparsityPattern Poisson< dim >::sparsity private
Definition at line 70 of file assembly_check.cc.
system_matrix
template<int dim> SparseMatrix< double > Poisson< dim >::system_matrix private
Definition at line 71 of file assembly_check.cc.
system_rhs
template<int dim> Vector< double > Poisson< dim >::system_rhs private
Definition at line 73 of file assembly_check.cc.
tria
template<int dim> Triangulation< dim > Poisson< dim >::tria private
Definition at line 65 of file assembly_check.cc.
The documentation for this class was generated from the following files:
/github/workspace/source/assembly_check.cc
/github/workspace/source/classical_dg_assembly.cc