PolyDEAL: Utils::LaplaceOperatorDG< dim, degree, n_qpoints, n_components, number > Class Template Reference
Utils::LaplaceOperatorDG< dim, degree, n_qpoints, n_components, number > Class Template Reference
#include <utils.h>
Public Types
using value_type = number
using VectorizedArrayType = VectorizedArray<number>
using VectorType = LinearAlgebra::distributed::Vector<number>
Public Member Functions
LaplaceOperatorDG ()
void reinit (const Mapping< dim > &mapping, const DoFHandler< dim > &dof_handler, const unsigned int level=numbers::invalid_unsigned_int)
void vmult (LinearAlgebra::distributed::Vector< number > &dst, const LinearAlgebra::distributed::Vector< number > &src) const
void Tvmult (LinearAlgebra::distributed::Vector< number > &dst, const LinearAlgebra::distributed::Vector< number > &src) const
void Tvmult_add (LinearAlgebra::distributed::Vector< number > &dst, const LinearAlgebra::distributed::Vector< number > &src) const
void vmult_add (LinearAlgebra::distributed::Vector< number > &dst, const LinearAlgebra::distributed::Vector< number > &src) const
types::global_dof_index m () const
types::global_dof_index n () const
number el (const unsigned int row, const unsigned int col) const
void initialize_dof_vector (LinearAlgebra::distributed::Vector< number > &vector) const
const DoFHandler< dim > & get_dof_handler () const
const Triangulation< dim > & get_triangulation () const
const LinearAlgebra::distributed::Vector< number > & get_matrix_diagonal_inverse () const
const MatrixFree< dim, number > * get_matrix_free () const
const TrilinosWrappers::SparseMatrix & get_system_matrix () const
void get_system_matrix (TrilinosWrappers::SparseMatrix &mg_matrix) const
void rhs (LinearAlgebra::distributed::Vector< number > &b) const
void compute_inverse_diagonal ()
Public Member Functions inherited from Subscriptor
Subscriptor ()
Subscriptor (const Subscriptor &)
Subscriptor (Subscriptor &&) noexcept
virtual ~Subscriptor ()
Subscriptor & operator= (const Subscriptor &)
Subscriptor & operator= (Subscriptor &&) noexcept
void serialize (Archive &ar, const unsigned int version)
void subscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
void unsubscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
unsigned int n_subscriptions () const
void list_subscribers (StreamType &stream) const
void list_subscribers () const
void subscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
void unsubscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
unsigned int n_subscriptions () const
void list_subscribers (StreamType &stream) const
void list_subscribers () const
Private Member Functions
void local_apply (const MatrixFree< dim, number > &data, LinearAlgebra::distributed::Vector< number > &dst, const LinearAlgebra::distributed::Vector< number > &src, const std::pair< unsigned int, unsigned int > &cell_range) const
void local_apply_face (const MatrixFree< dim, number > &data, LinearAlgebra::distributed::Vector< number > &dst, const LinearAlgebra::distributed::Vector< number > &src, const std::pair< unsigned int, unsigned int > &face_range) const
void local_apply_boundary (const MatrixFree< dim, number > &data, LinearAlgebra::distributed::Vector< number > &dst, const LinearAlgebra::distributed::Vector< number > &src, const std::pair< unsigned int, unsigned int > &face_range) const
void local_diagonal_cell (const MatrixFree< dim, number > &data, LinearAlgebra::distributed::Vector< number > &dst, const unsigned int &, const std::pair< unsigned int, unsigned int > &cell_range) const
void local_diagonal_face (const MatrixFree< dim, number > &data, LinearAlgebra::distributed::Vector< number > &dst, const unsigned int &, const std::pair< unsigned int, unsigned int > &face_range) const
void local_diagonal_boundary (const MatrixFree< dim, number > &data, LinearAlgebra::distributed::Vector< number > &dst, const unsigned int &, const std::pair< unsigned int, unsigned int > &face_range) const
Private Attributes
MatrixFree< dim, number > data
LinearAlgebra::distributed::Vector< number > inverse_diagonal_entries
int fe_degree
TrilinosWrappers::SparseMatrix system_matrix
AffineConstraints< number > constraints
Additional Inherited Members
Static Public Member Functions inherited from Subscriptor
static ::ExceptionBase & ExcInUse (int arg1, std::string arg2, std::string arg3)
static ::ExceptionBase & ExcNoSubscriber (std::string arg1, std::string arg2)
Detailed Description
template<int dim, int degree, int n_qpoints, int n_components, typename number = double>
class Utils::LaplaceOperatorDG< dim, degree, n_qpoints, n_components, number >
Class that implements the action of symmetric interior penalty operator on a vector.
Note
The member function rhs() assume the source term is 1. Different source terms can be defined by suitably changing that function.
Definition at line 363 of file utils.h.
Member Typedef Documentation
value_type
template<int dim, int degree, int n_qpoints, int n_components, typename number = double> using Utils::LaplaceOperatorDG< dim, degree, n_qpoints, n_components, number >::value_type = number
Definition at line 366 of file utils.h.
VectorizedArrayType
template<int dim, int degree, int n_qpoints, int n_components, typename number = double> using Utils::LaplaceOperatorDG< dim, degree, n_qpoints, n_components, number >::VectorizedArrayType = VectorizedArray<number>
Definition at line 367 of file utils.h.
VectorType
template<int dim, int degree, int n_qpoints, int n_components, typename number = double> using Utils::LaplaceOperatorDG< dim, degree, n_qpoints, n_components, number >::VectorType = LinearAlgebra::distributed::Vector<number>
Definition at line 368 of file utils.h.
Constructor & Destructor Documentation
LaplaceOperatorDG()
template<int dim, int degree, int n_qpoints, int n_components, typename number = double> Utils::LaplaceOperatorDG< dim, degree, n_qpoints, n_components, number >::LaplaceOperatorDG () inline
Definition at line 371 of file utils.h.
Member Function Documentation
compute_inverse_diagonal()
template<int dim, int degree, int n_qpoints, int n_components, typename number = double> void Utils::LaplaceOperatorDG< dim, degree, n_qpoints, n_components, number >::compute_inverse_diagonal () inline
Definition at line 765 of file utils.h.
References std::abs(), Utils::LaplaceOperatorDG< dim, degree, n_qpoints, n_components, number >::data, e(), Utils::LaplaceOperatorDG< dim, degree, n_qpoints, n_components, number >::inverse_diagonal_entries, Utils::LaplaceOperatorDG< dim, degree, n_qpoints, n_components, number >::local_diagonal_boundary(), Utils::LaplaceOperatorDG< dim, degree, n_qpoints, n_components, number >::local_diagonal_cell(), and Utils::LaplaceOperatorDG< dim, degree, n_qpoints, n_components, number >::local_diagonal_face().
Referenced by Utils::LaplaceOperatorDG< dim, degree, n_qpoints, n_components, number >::reinit().
el()
template<int dim, int degree, int n_qpoints, int n_components, typename number = double> number Utils::LaplaceOperatorDG< dim, degree, n_qpoints, n_components, number >::el (const unsigned int row, const unsigned int col) const inline
Definition at line 463 of file utils.h.
References AssertThrow.
get_dof_handler()
template<int dim, int degree, int n_qpoints, int n_components, typename number = double> const DoFHandler< dim > & Utils::LaplaceOperatorDG< dim, degree, n_qpoints, n_components, number >::get_dof_handler () const inline
Definition at line 481 of file utils.h.
References Utils::LaplaceOperatorDG< dim, degree, n_qpoints, n_components, number >::data.
get_matrix_diagonal_inverse()
template<int dim, int degree, int n_qpoints, int n_components, typename number = double> const LinearAlgebra::distributed::Vector< number > & Utils::LaplaceOperatorDG< dim, degree, n_qpoints, n_components, number >::get_matrix_diagonal_inverse () const inline
Definition at line 494 of file utils.h.
References Utils::LaplaceOperatorDG< dim, degree, n_qpoints, n_components, number >::inverse_diagonal_entries.
get_matrix_free()
template<int dim, int degree, int n_qpoints, int n_components, typename number = double> const MatrixFree< dim, number > * Utils::LaplaceOperatorDG< dim, degree, n_qpoints, n_components, number >::get_matrix_free () const inline
Definition at line 501 of file utils.h.
References Utils::LaplaceOperatorDG< dim, degree, n_qpoints, n_components, number >::data.
get_system_matrix() [1/2]
template<int dim, int degree, int n_qpoints, int n_components, typename number = double> const TrilinosWrappers::SparseMatrix & Utils::LaplaceOperatorDG< dim, degree, n_qpoints, n_components, number >::get_system_matrix () const inline
Definition at line 509 of file utils.h.
References std::abs(), TrilinosWrappers::SparsityPattern::compress(), MatrixFreeTools::compute_matrix(), Utils::LaplaceOperatorDG< dim, degree, n_qpoints, n_components, number >::constraints, Utils::LaplaceOperatorDG< dim, degree, n_qpoints, n_components, number >::data, Utils::LaplaceOperatorDG< dim, degree, n_qpoints, n_components, number >::fe_degree, EvaluationFlags::gradients, numbers::invalid_unsigned_int, TrilinosWrappers::SparseMatrix::m(), DoFTools::make_flux_sparsity_pattern(), MGTools::make_flux_sparsity_pattern(), std::max(), TrilinosWrappers::SparseMatrix::n(), TrilinosWrappers::SparseMatrix::reinit(), Utils::LaplaceOperatorDG< dim, degree, n_qpoints, n_components, number >::system_matrix, and EvaluationFlags::values.
get_system_matrix() [2/2]
template<int dim, int degree, int n_qpoints, int n_components, typename number = double> void Utils::LaplaceOperatorDG< dim, degree, n_qpoints, n_components, number >::get_system_matrix (TrilinosWrappers::SparseMatrix & mg_matrix) const inline
Definition at line 617 of file utils.h.
References std::abs(), AssertThrow, MatrixFreeTools::compute_matrix(), Utils::LaplaceOperatorDG< dim, degree, n_qpoints, n_components, number >::constraints, Utils::LaplaceOperatorDG< dim, degree, n_qpoints, n_components, number >::data, SparsityTools::distribute_sparsity_pattern(), DoFTools::extract_locally_relevant_dofs(), Utils::LaplaceOperatorDG< dim, degree, n_qpoints, n_components, number >::fe_degree, EvaluationFlags::gradients, DoFHandler< int dim, int spacedim >::locally_owned_dofs(), TrilinosWrappers::SparseMatrix::m(), DoFTools::make_flux_sparsity_pattern(), std::max(), TrilinosWrappers::SparseMatrix::n(), DoFHandler< int dim, int spacedim >::n_dofs(), TrilinosWrappers::SparseMatrix::reinit(), and EvaluationFlags::values.
get_triangulation()
template<int dim, int degree, int n_qpoints, int n_components, typename number = double> const Triangulation< dim > & Utils::LaplaceOperatorDG< dim, degree, n_qpoints, n_components, number >::get_triangulation () const inline
Definition at line 488 of file utils.h.
References Utils::LaplaceOperatorDG< dim, degree, n_qpoints, n_components, number >::data, and Triangulation< int dim, int spacedim >::get_triangulation().
initialize_dof_vector()
template<int dim, int degree, int n_qpoints, int n_components, typename number = double> void Utils::LaplaceOperatorDG< dim, degree, n_qpoints, n_components, number >::initialize_dof_vector (LinearAlgebra::distributed::Vector< number > & vector) const inline
Definition at line 473 of file utils.h.
References Utils::LaplaceOperatorDG< dim, degree, n_qpoints, n_components, number >::data.
local_apply()
template<int dim, int degree, int n_qpoints, int n_components, typename number = double> void Utils::LaplaceOperatorDG< dim, degree, n_qpoints, n_components, number >::local_apply (const MatrixFree< dim, number > & data, LinearAlgebra::distributed::Vector< number > & dst, const LinearAlgebra::distributed::Vector< number > & src, const std::pair< unsigned int, unsigned int > & cell_range) const inline private
Definition at line 787 of file utils.h.
References Utils::LaplaceOperatorDG< dim, degree, n_qpoints, n_components, number >::data, and EvaluationFlags::gradients.
Referenced by Utils::LaplaceOperatorDG< dim, degree, n_qpoints, n_components, number >::vmult_add().
local_apply_boundary()
template<int dim, int degree, int n_qpoints, int n_components, typename number = double> void Utils::LaplaceOperatorDG< dim, degree, n_qpoints, n_components, number >::local_apply_boundary (const MatrixFree< dim, number > & data, LinearAlgebra::distributed::Vector< number > & dst, const LinearAlgebra::distributed::Vector< number > & src, const std::pair< unsigned int, unsigned int > & face_range) const inline private
Definition at line 860 of file utils.h.
References std::abs(), Utils::LaplaceOperatorDG< dim, degree, n_qpoints, n_components, number >::data, Utils::LaplaceOperatorDG< dim, degree, n_qpoints, n_components, number >::fe_degree, EvaluationFlags::gradients, std::max(), and EvaluationFlags::values.
Referenced by Utils::LaplaceOperatorDG< dim, degree, n_qpoints, n_components, number >::vmult_add().
local_apply_face()
template<int dim, int degree, int n_qpoints, int n_components, typename number = double> void Utils::LaplaceOperatorDG< dim, degree, n_qpoints, n_components, number >::local_apply_face (const MatrixFree< dim, number > & data, LinearAlgebra::distributed::Vector< number > & dst, const LinearAlgebra::distributed::Vector< number > & src, const std::pair< unsigned int, unsigned int > & face_range) const inline private
Definition at line 808 of file utils.h.
References std::abs(), Utils::LaplaceOperatorDG< dim, degree, n_qpoints, n_components, number >::data, Utils::LaplaceOperatorDG< dim, degree, n_qpoints, n_components, number >::fe_degree, EvaluationFlags::gradients, std::max(), and EvaluationFlags::values.
Referenced by Utils::LaplaceOperatorDG< dim, degree, n_qpoints, n_components, number >::vmult_add().
local_diagonal_boundary()
template<int dim, int degree, int n_qpoints, int n_components, typename number = double> void Utils::LaplaceOperatorDG< dim, degree, n_qpoints, n_components, number >::local_diagonal_boundary (const MatrixFree< dim, number > & data, LinearAlgebra::distributed::Vector< number > & dst, const unsigned int & , const std::pair< unsigned int, unsigned int > & face_range) const inline private
Definition at line 1022 of file utils.h.
References std::abs(), Utils::LaplaceOperatorDG< dim, degree, n_qpoints, n_components, number >::data, Utils::LaplaceOperatorDG< dim, degree, n_qpoints, n_components, number >::fe_degree, EvaluationFlags::gradients, std::max(), and EvaluationFlags::values.
Referenced by Utils::LaplaceOperatorDG< dim, degree, n_qpoints, n_components, number >::compute_inverse_diagonal().
local_diagonal_cell()
template<int dim, int degree, int n_qpoints, int n_components, typename number = double> void Utils::LaplaceOperatorDG< dim, degree, n_qpoints, n_components, number >::local_diagonal_cell (const MatrixFree< dim, number > & data, LinearAlgebra::distributed::Vector< number > & dst, const unsigned int & , const std::pair< unsigned int, unsigned int > & cell_range) const inline private
Definition at line 897 of file utils.h.
References Utils::LaplaceOperatorDG< dim, degree, n_qpoints, n_components, number >::data, and EvaluationFlags::gradients.
Referenced by Utils::LaplaceOperatorDG< dim, degree, n_qpoints, n_components, number >::compute_inverse_diagonal().
local_diagonal_face()
template<int dim, int degree, int n_qpoints, int n_components, typename number = double> void Utils::LaplaceOperatorDG< dim, degree, n_qpoints, n_components, number >::local_diagonal_face (const MatrixFree< dim, number > & data, LinearAlgebra::distributed::Vector< number > & dst, const unsigned int & , const std::pair< unsigned int, unsigned int > & face_range) const inline private
Definition at line 930 of file utils.h.
References std::abs(), Utils::LaplaceOperatorDG< dim, degree, n_qpoints, n_components, number >::data, Utils::LaplaceOperatorDG< dim, degree, n_qpoints, n_components, number >::fe_degree, EvaluationFlags::gradients, std::max(), and EvaluationFlags::values.
Referenced by Utils::LaplaceOperatorDG< dim, degree, n_qpoints, n_components, number >::compute_inverse_diagonal().
m()
template<int dim, int degree, int n_qpoints, int n_components, typename number = double> types::global_dof_index Utils::LaplaceOperatorDG< dim, degree, n_qpoints, n_components, number >::m () const inline
Definition at line 451 of file utils.h.
References Utils::LaplaceOperatorDG< dim, degree, n_qpoints, n_components, number >::data.
n()
template<int dim, int degree, int n_qpoints, int n_components, typename number = double> types::global_dof_index Utils::LaplaceOperatorDG< dim, degree, n_qpoints, n_components, number >::n () const inline
Definition at line 457 of file utils.h.
References Utils::LaplaceOperatorDG< dim, degree, n_qpoints, n_components, number >::data.
reinit()
template<int dim, int degree, int n_qpoints, int n_components, typename number = double> void Utils::LaplaceOperatorDG< dim, degree, n_qpoints, n_components, number >::reinit (const Mapping< dim > & mapping, const DoFHandler< dim > & dof_handler, const unsigned int level = numbers::invalid_unsigned_int) inline
Definition at line 374 of file utils.h.
References Utils::LaplaceOperatorDG< dim, degree, n_qpoints, n_components, number >::compute_inverse_diagonal(), Utils::LaplaceOperatorDG< dim, degree, n_qpoints, n_components, number >::constraints, Utils::LaplaceOperatorDG< dim, degree, n_qpoints, n_components, number >::data, FiniteElement< int dim, int spacedim >::degree, Utils::LaplaceOperatorDG< dim, degree, n_qpoints, n_components, number >::fe_degree, DoFHandler< int dim, int spacedim >::get_fe(), level, MatrixFree::AdditionalData::mapping_update_flags_boundary_faces, MatrixFree::AdditionalData::mapping_update_flags_inner_faces, MatrixFree::AdditionalData::mg_level, MatrixFree::AdditionalData::tasks_block_size, MatrixFree::AdditionalData::tasks_parallel_scheme, update_gradients, and update_JxW_values.
rhs()
template<int dim, int degree, int n_qpoints, int n_components, typename number = double> void Utils::LaplaceOperatorDG< dim, degree, n_qpoints, n_components, number >::rhs (LinearAlgebra::distributed::Vector< number > & b) const inline
Definition at line 722 of file utils.h.
References b(), Utils::LaplaceOperatorDG< dim, degree, n_qpoints, n_components, number >::data, and EvaluationFlags::values.
Tvmult()
template<int dim, int degree, int n_qpoints, int n_components, typename number = double> void Utils::LaplaceOperatorDG< dim, degree, n_qpoints, n_components, number >::Tvmult (LinearAlgebra::distributed::Vector< number > & dst, const LinearAlgebra::distributed::Vector< number > & src) const inline
Definition at line 406 of file utils.h.
References Utils::LaplaceOperatorDG< dim, degree, n_qpoints, n_components, number >::vmult_add().
Tvmult_add()
template<int dim, int degree, int n_qpoints, int n_components, typename number = double> void Utils::LaplaceOperatorDG< dim, degree, n_qpoints, n_components, number >::Tvmult_add (LinearAlgebra::distributed::Vector< number > & dst, const LinearAlgebra::distributed::Vector< number > & src) const inline
Definition at line 414 of file utils.h.
References Utils::LaplaceOperatorDG< dim, degree, n_qpoints, n_components, number >::vmult_add().
vmult()
template<int dim, int degree, int n_qpoints, int n_components, typename number = double> void Utils::LaplaceOperatorDG< dim, degree, n_qpoints, n_components, number >::vmult (LinearAlgebra::distributed::Vector< number > & dst, const LinearAlgebra::distributed::Vector< number > & src) const inline
Definition at line 398 of file utils.h.
References Utils::LaplaceOperatorDG< dim, degree, n_qpoints, n_components, number >::vmult_add().
vmult_add()
template<int dim, int degree, int n_qpoints, int n_components, typename number = double> void Utils::LaplaceOperatorDG< dim, degree, n_qpoints, n_components, number >::vmult_add (LinearAlgebra::distributed::Vector< number > & dst, const LinearAlgebra::distributed::Vector< number > & src) const inline
Definition at line 421 of file utils.h.
References Utils::LaplaceOperatorDG< dim, degree, n_qpoints, n_components, number >::data, Utils::LaplaceOperatorDG< dim, degree, n_qpoints, n_components, number >::local_apply(), Utils::LaplaceOperatorDG< dim, degree, n_qpoints, n_components, number >::local_apply_boundary(), Utils::LaplaceOperatorDG< dim, degree, n_qpoints, n_components, number >::local_apply_face(), LinearAlgebra::distributed::Vector< typename Number, typename MemorySpace >::partitioners_are_globally_compatible(), LinearAlgebra::distributed::Vector< typename Number, typename MemorySpace >::reinit(), LinearAlgebra::distributed::Vector< typename Number, typename MemorySpace >::swap(), swap(), and LinearAlgebra::distributed::Vector< typename Number, typename MemorySpace >::zero_out_ghost_values().
Referenced by Utils::LaplaceOperatorDG< dim, degree, n_qpoints, n_components, number >::Tvmult(), Utils::LaplaceOperatorDG< dim, degree, n_qpoints, n_components, number >::Tvmult_add(), and Utils::LaplaceOperatorDG< dim, degree, n_qpoints, n_components, number >::vmult().
Member Data Documentation
constraints
template<int dim, int degree, int n_qpoints, int n_components, typename number = double> AffineConstraints<number> Utils::LaplaceOperatorDG< dim, degree, n_qpoints, n_components, number >::constraints private
Definition at line 1076 of file utils.h.
Referenced by Utils::LaplaceOperatorDG< dim, degree, n_qpoints, n_components, number >::get_system_matrix(), Utils::LaplaceOperatorDG< dim, degree, n_qpoints, n_components, number >::get_system_matrix(), and Utils::LaplaceOperatorDG< dim, degree, n_qpoints, n_components, number >::reinit().
data
template<int dim, int degree, int n_qpoints, int n_components, typename number = double> MatrixFree<dim, number> Utils::LaplaceOperatorDG< dim, degree, n_qpoints, n_components, number >::data private
Definition at line 1072 of file utils.h.
Referenced by Utils::LaplaceOperatorDG< dim, degree, n_qpoints, n_components, number >::compute_inverse_diagonal(), Utils::LaplaceOperatorDG< dim, degree, n_qpoints, n_components, number >::get_dof_handler(), Utils::LaplaceOperatorDG< dim, degree, n_qpoints, n_components, number >::get_matrix_free(), Utils::LaplaceOperatorDG< dim, degree, n_qpoints, n_components, number >::get_system_matrix(), Utils::LaplaceOperatorDG< dim, degree, n_qpoints, n_components, number >::get_system_matrix(), Utils::LaplaceOperatorDG< dim, degree, n_qpoints, n_components, number >::get_triangulation(), Utils::LaplaceOperatorDG< dim, degree, n_qpoints, n_components, number >::initialize_dof_vector(), Utils::LaplaceOperatorDG< dim, degree, n_qpoints, n_components, number >::local_apply(), Utils::LaplaceOperatorDG< dim, degree, n_qpoints, n_components, number >::local_apply_boundary(), Utils::LaplaceOperatorDG< dim, degree, n_qpoints, n_components, number >::local_apply_face(), Utils::LaplaceOperatorDG< dim, degree, n_qpoints, n_components, number >::local_diagonal_boundary(), Utils::LaplaceOperatorDG< dim, degree, n_qpoints, n_components, number >::local_diagonal_cell(), Utils::LaplaceOperatorDG< dim, degree, n_qpoints, n_components, number >::local_diagonal_face(), Utils::LaplaceOperatorDG< dim, degree, n_qpoints, n_components, number >::m(), Utils::LaplaceOperatorDG< dim, degree, n_qpoints, n_components, number >::n(), Utils::LaplaceOperatorDG< dim, degree, n_qpoints, n_components, number >::reinit(), Utils::LaplaceOperatorDG< dim, degree, n_qpoints, n_components, number >::rhs(), and Utils::LaplaceOperatorDG< dim, degree, n_qpoints, n_components, number >::vmult_add().
fe_degree
template<int dim, int degree, int n_qpoints, int n_components, typename number = double> int Utils::LaplaceOperatorDG< dim, degree, n_qpoints, n_components, number >::fe_degree private
Definition at line 1074 of file utils.h.
Referenced by Utils::LaplaceOperatorDG< dim, degree, n_qpoints, n_components, number >::get_system_matrix(), Utils::LaplaceOperatorDG< dim, degree, n_qpoints, n_components, number >::get_system_matrix(), Utils::LaplaceOperatorDG< dim, degree, n_qpoints, n_components, number >::local_apply_boundary(), Utils::LaplaceOperatorDG< dim, degree, n_qpoints, n_components, number >::local_apply_face(), Utils::LaplaceOperatorDG< dim, degree, n_qpoints, n_components, number >::local_diagonal_boundary(), Utils::LaplaceOperatorDG< dim, degree, n_qpoints, n_components, number >::local_diagonal_face(), and Utils::LaplaceOperatorDG< dim, degree, n_qpoints, n_components, number >::reinit().
inverse_diagonal_entries
template<int dim, int degree, int n_qpoints, int n_components, typename number = double> LinearAlgebra::distributed::Vector<number> Utils::LaplaceOperatorDG< dim, degree, n_qpoints, n_components, number >::inverse_diagonal_entries private
Definition at line 1073 of file utils.h.
Referenced by Utils::LaplaceOperatorDG< dim, degree, n_qpoints, n_components, number >::compute_inverse_diagonal(), and Utils::LaplaceOperatorDG< dim, degree, n_qpoints, n_components, number >::get_matrix_diagonal_inverse().
system_matrix
template<int dim, int degree, int n_qpoints, int n_components, typename number = double> TrilinosWrappers::SparseMatrix Utils::LaplaceOperatorDG< dim, degree, n_qpoints, n_components, number >::system_matrix mutable private
Definition at line 1075 of file utils.h.
Referenced by Utils::LaplaceOperatorDG< dim, degree, n_qpoints, n_components, number >::get_system_matrix().
The documentation for this class was generated from the following file:
/github/workspace/include/utils.h