PolyDEAL: Utils::MatrixFreeOperators::LaplaceOperatorDG< dim, degree, n_q_points, n_components, number > Class Template Reference
Utils::MatrixFreeOperators::LaplaceOperatorDG< dim, degree, n_q_points, n_components, number > Class Template Reference
#include <utils.h>
Public Types
using value_type = number
using VectorizedArrayType = VectorizedArray<number>
using VectorType = LinearAlgebra::distributed::Vector<number>
Public Member Functions
LaplaceOperatorDG ()
void reinit (const Mapping< dim > &mapping, const DoFHandler< dim > &dof_handler, const unsigned int level=numbers::invalid_unsigned_int)
void vmult (LinearAlgebra::distributed::Vector< number > &dst, const LinearAlgebra::distributed::Vector< number > &src) const
void Tvmult (LinearAlgebra::distributed::Vector< number > &dst, const LinearAlgebra::distributed::Vector< number > &src) const
void Tvmult_add (LinearAlgebra::distributed::Vector< number > &dst, const LinearAlgebra::distributed::Vector< number > &src) const
void vmult_add (LinearAlgebra::distributed::Vector< number > &dst, const LinearAlgebra::distributed::Vector< number > &src) const
types::global_dof_index m () const
types::global_dof_index n () const
number el (const unsigned int row, const unsigned int col) const
void initialize_dof_vector (LinearAlgebra::distributed::Vector< number > &vector) const
const DoFHandler< dim > & get_dof_handler () const
const Triangulation< dim > & get_triangulation () const
const LinearAlgebra::distributed::Vector< number > & get_matrix_diagonal_inverse () const
const MatrixFree< dim, number > * get_matrix_free () const
const TrilinosWrappers::SparseMatrix & get_system_matrix () const
void get_system_matrix (TrilinosWrappers::SparseMatrix &mg_matrix) const
void rhs (LinearAlgebra::distributed::Vector< number > &b) const
void compute_inverse_diagonal ()
Public Member Functions inherited from EnableObserverPointer
EnableObserverPointer ()
EnableObserverPointer (const EnableObserverPointer &)
EnableObserverPointer (EnableObserverPointer &&) noexcept
virtual ~EnableObserverPointer ()
EnableObserverPointer & operator= (const EnableObserverPointer &)
EnableObserverPointer & operator= (EnableObserverPointer &&) noexcept
void serialize (Archive &ar, const unsigned int version)
unsigned int n_subscriptions () const
void list_subscribers (StreamType &stream) const
void list_subscribers () const
unsigned int n_subscriptions () const
void list_subscribers (StreamType &stream) const
void list_subscribers () const
Private Member Functions
void local_apply (const MatrixFree< dim, number > &data, LinearAlgebra::distributed::Vector< number > &dst, const LinearAlgebra::distributed::Vector< number > &src, const std::pair< unsigned int, unsigned int > &cell_range) const
void local_apply_face (const MatrixFree< dim, number > &data, LinearAlgebra::distributed::Vector< number > &dst, const LinearAlgebra::distributed::Vector< number > &src, const std::pair< unsigned int, unsigned int > &face_range) const
void local_apply_boundary (const MatrixFree< dim, number > &data, LinearAlgebra::distributed::Vector< number > &dst, const LinearAlgebra::distributed::Vector< number > &src, const std::pair< unsigned int, unsigned int > &face_range) const
void local_diagonal_cell (const MatrixFree< dim, number > &data, LinearAlgebra::distributed::Vector< number > &dst, const unsigned int &, const std::pair< unsigned int, unsigned int > &cell_range) const
void local_diagonal_face (const MatrixFree< dim, number > &data, LinearAlgebra::distributed::Vector< number > &dst, const unsigned int &, const std::pair< unsigned int, unsigned int > &face_range) const
void local_diagonal_boundary (const MatrixFree< dim, number > &data, LinearAlgebra::distributed::Vector< number > &dst, const unsigned int &, const std::pair< unsigned int, unsigned int > &face_range) const
Private Attributes
MatrixFree< dim, number > data
LinearAlgebra::distributed::Vector< number > inverse_diagonal_entries
int fe_degree
TrilinosWrappers::SparseMatrix system_matrix
AffineConstraints< number > constraints
Additional Inherited Members
Static Public Member Functions inherited from EnableObserverPointer
static ::ExceptionBase & ExcInUse (int arg1, std::string arg2, std::string arg3)
static ::ExceptionBase & ExcNoSubscriber (std::string arg1, std::string arg2)
Detailed Description
template<int dim, int degree, int n_q_points, int n_components, typename number = double>
class Utils::MatrixFreeOperators::LaplaceOperatorDG< dim, degree, n_q_points, n_components, number >
Class that implements the action of symmetric interior penalty operator on a vector.
Note
The member function rhs() assume the source term is 1. Different source terms can be defined by suitably changing that function.
Definition at line 380 of file utils.h.
Member Typedef Documentation
value_type
template<int dim, int degree, int n_q_points, int n_components, typename number = double> using Utils::MatrixFreeOperators::LaplaceOperatorDG< dim, degree, n_q_points, n_components, number >::value_type = number
Definition at line 383 of file utils.h.
VectorizedArrayType
template<int dim, int degree, int n_q_points, int n_components, typename number = double> using Utils::MatrixFreeOperators::LaplaceOperatorDG< dim, degree, n_q_points, n_components, number >::VectorizedArrayType = VectorizedArray<number>
Definition at line 384 of file utils.h.
VectorType
template<int dim, int degree, int n_q_points, int n_components, typename number = double> using Utils::MatrixFreeOperators::LaplaceOperatorDG< dim, degree, n_q_points, n_components, number >::VectorType = LinearAlgebra::distributed::Vector<number>
Definition at line 385 of file utils.h.
Constructor & Destructor Documentation
LaplaceOperatorDG()
template<int dim, int degree, int n_q_points, int n_components, typename number = double> Utils::MatrixFreeOperators::LaplaceOperatorDG< dim, degree, n_q_points, n_components, number >::LaplaceOperatorDG () inline
Definition at line 388 of file utils.h.
Member Function Documentation
compute_inverse_diagonal()
template<int dim, int degree, int n_q_points, int n_components, typename number = double> void Utils::MatrixFreeOperators::LaplaceOperatorDG< dim, degree, n_q_points, n_components, number >::compute_inverse_diagonal () inline
Definition at line 789 of file utils.h.
References std::abs(), data, inverse_diagonal_entries, local_diagonal_boundary(), local_diagonal_cell(), and local_diagonal_face().
Referenced by reinit().
el()
template<int dim, int degree, int n_q_points, int n_components, typename number = double> number Utils::MatrixFreeOperators::LaplaceOperatorDG< dim, degree, n_q_points, n_components, number >::el (const unsigned int row, const unsigned int col) const inline
Definition at line 480 of file utils.h.
get_dof_handler()
template<int dim, int degree, int n_q_points, int n_components, typename number = double> const DoFHandler< dim > & Utils::MatrixFreeOperators::LaplaceOperatorDG< dim, degree, n_q_points, n_components, number >::get_dof_handler () const inline
Definition at line 498 of file utils.h.
References data.
get_matrix_diagonal_inverse()
template<int dim, int degree, int n_q_points, int n_components, typename number = double> const LinearAlgebra::distributed::Vector< number > & Utils::MatrixFreeOperators::LaplaceOperatorDG< dim, degree, n_q_points, n_components, number >::get_matrix_diagonal_inverse () const inline
Definition at line 511 of file utils.h.
References inverse_diagonal_entries.
get_matrix_free()
template<int dim, int degree, int n_q_points, int n_components, typename number = double> const MatrixFree< dim, number > * Utils::MatrixFreeOperators::LaplaceOperatorDG< dim, degree, n_q_points, n_components, number >::get_matrix_free () const inline
Definition at line 518 of file utils.h.
References data.
get_system_matrix() [1/2]
template<int dim, int degree, int n_q_points, int n_components, typename number = double> const TrilinosWrappers::SparseMatrix & Utils::MatrixFreeOperators::LaplaceOperatorDG< dim, degree, n_q_points, n_components, number >::get_system_matrix () const inline
Definition at line 526 of file utils.h.
References std::abs(), TrilinosWrappers::SparsityPattern::compress(), MatrixFreeTools::compute_matrix(), constraints, data, fe_degree, EvaluationFlags::gradients, numbers::invalid_unsigned_int, DoFTools::make_flux_sparsity_pattern(), MGTools::make_flux_sparsity_pattern(), std::max(), system_matrix, and EvaluationFlags::values.
get_system_matrix() [2/2]
template<int dim, int degree, int n_q_points, int n_components, typename number = double> void Utils::MatrixFreeOperators::LaplaceOperatorDG< dim, degree, n_q_points, n_components, number >::get_system_matrix (TrilinosWrappers::SparseMatrix & mg_matrix) const inline
Definition at line 636 of file utils.h.
References std::abs(), MatrixFreeTools::compute_matrix(), constraints, data, SparsityTools::distribute_sparsity_pattern(), DoFTools::extract_locally_relevant_dofs(), fe_degree, EvaluationFlags::gradients, DoFHandler< int dim, int spacedim >::locally_owned_dofs(), TrilinosWrappers::SparseMatrix::m(), DoFTools::make_flux_sparsity_pattern(), std::max(), TrilinosWrappers::SparseMatrix::n(), DoFHandler< int dim, int spacedim >::n_dofs(), TrilinosWrappers::SparseMatrix::reinit(), and EvaluationFlags::values.
get_triangulation()
template<int dim, int degree, int n_q_points, int n_components, typename number = double> const Triangulation< dim > & Utils::MatrixFreeOperators::LaplaceOperatorDG< dim, degree, n_q_points, n_components, number >::get_triangulation () const inline
Definition at line 505 of file utils.h.
References data.
initialize_dof_vector()
template<int dim, int degree, int n_q_points, int n_components, typename number = double> void Utils::MatrixFreeOperators::LaplaceOperatorDG< dim, degree, n_q_points, n_components, number >::initialize_dof_vector (LinearAlgebra::distributed::Vector< number > & vector) const inline
Definition at line 490 of file utils.h.
References data.
local_apply()
template<int dim, int degree, int n_q_points, int n_components, typename number = double> void Utils::MatrixFreeOperators::LaplaceOperatorDG< dim, degree, n_q_points, n_components, number >::local_apply (const MatrixFree< dim, number > & data, LinearAlgebra::distributed::Vector< number > & dst, const LinearAlgebra::distributed::Vector< number > & src, const std::pair< unsigned int, unsigned int > & cell_range) const inline private
Definition at line 811 of file utils.h.
References data, and EvaluationFlags::gradients.
Referenced by vmult_add().
local_apply_boundary()
template<int dim, int degree, int n_q_points, int n_components, typename number = double> void Utils::MatrixFreeOperators::LaplaceOperatorDG< dim, degree, n_q_points, n_components, number >::local_apply_boundary (const MatrixFree< dim, number > & data, LinearAlgebra::distributed::Vector< number > & dst, const LinearAlgebra::distributed::Vector< number > & src, const std::pair< unsigned int, unsigned int > & face_range) const inline private
Definition at line 884 of file utils.h.
References std::abs(), data, fe_degree, EvaluationFlags::gradients, std::max(), and EvaluationFlags::values.
Referenced by vmult_add().
local_apply_face()
template<int dim, int degree, int n_q_points, int n_components, typename number = double> void Utils::MatrixFreeOperators::LaplaceOperatorDG< dim, degree, n_q_points, n_components, number >::local_apply_face (const MatrixFree< dim, number > & data, LinearAlgebra::distributed::Vector< number > & dst, const LinearAlgebra::distributed::Vector< number > & src, const std::pair< unsigned int, unsigned int > & face_range) const inline private
Definition at line 832 of file utils.h.
References std::abs(), data, fe_degree, EvaluationFlags::gradients, std::max(), and EvaluationFlags::values.
Referenced by vmult_add().
local_diagonal_boundary()
template<int dim, int degree, int n_q_points, int n_components, typename number = double> void Utils::MatrixFreeOperators::LaplaceOperatorDG< dim, degree, n_q_points, n_components, number >::local_diagonal_boundary (const MatrixFree< dim, number > & data, LinearAlgebra::distributed::Vector< number > & dst, const unsigned int & , const std::pair< unsigned int, unsigned int > & face_range) const inline private
Definition at line 1046 of file utils.h.
References std::abs(), data, fe_degree, EvaluationFlags::gradients, std::max(), and EvaluationFlags::values.
Referenced by compute_inverse_diagonal().
local_diagonal_cell()
template<int dim, int degree, int n_q_points, int n_components, typename number = double> void Utils::MatrixFreeOperators::LaplaceOperatorDG< dim, degree, n_q_points, n_components, number >::local_diagonal_cell (const MatrixFree< dim, number > & data, LinearAlgebra::distributed::Vector< number > & dst, const unsigned int & , const std::pair< unsigned int, unsigned int > & cell_range) const inline private
Definition at line 921 of file utils.h.
References data, and EvaluationFlags::gradients.
Referenced by compute_inverse_diagonal().
local_diagonal_face()
template<int dim, int degree, int n_q_points, int n_components, typename number = double> void Utils::MatrixFreeOperators::LaplaceOperatorDG< dim, degree, n_q_points, n_components, number >::local_diagonal_face (const MatrixFree< dim, number > & data, LinearAlgebra::distributed::Vector< number > & dst, const unsigned int & , const std::pair< unsigned int, unsigned int > & face_range) const inline private
Definition at line 954 of file utils.h.
References std::abs(), data, fe_degree, EvaluationFlags::gradients, std::max(), and EvaluationFlags::values.
Referenced by compute_inverse_diagonal().
m()
template<int dim, int degree, int n_q_points, int n_components, typename number = double> types::global_dof_index Utils::MatrixFreeOperators::LaplaceOperatorDG< dim, degree, n_q_points, n_components, number >::m () const inline
Definition at line 468 of file utils.h.
References data.
n()
template<int dim, int degree, int n_q_points, int n_components, typename number = double> types::global_dof_index Utils::MatrixFreeOperators::LaplaceOperatorDG< dim, degree, n_q_points, n_components, number >::n () const inline
Definition at line 474 of file utils.h.
References data.
reinit()
template<int dim, int degree, int n_q_points, int n_components, typename number = double> void Utils::MatrixFreeOperators::LaplaceOperatorDG< dim, degree, n_q_points, n_components, number >::reinit (const Mapping< dim > & mapping, const DoFHandler< dim > & dof_handler, const unsigned int level = numbers::invalid_unsigned_int) inline
Definition at line 391 of file utils.h.
References compute_inverse_diagonal(), constraints, data, FiniteElement< int dim, int spacedim >::degree, fe_degree, DoFHandler< int dim, int spacedim >::get_fe(), numbers::invalid_unsigned_int, MatrixFree::AdditionalData::mapping_update_flags_boundary_faces, MatrixFree::AdditionalData::mapping_update_flags_inner_faces, MatrixFree::AdditionalData::mg_level, MatrixFree::AdditionalData::none, MatrixFree::AdditionalData::tasks_block_size, and MatrixFree::AdditionalData::tasks_parallel_scheme.
rhs()
template<int dim, int degree, int n_q_points, int n_components, typename number = double> void Utils::MatrixFreeOperators::LaplaceOperatorDG< dim, degree, n_q_points, n_components, number >::rhs (LinearAlgebra::distributed::Vector< number > & b) const inline
Definition at line 742 of file utils.h.
References data, and EvaluationFlags::values.
Tvmult()
template<int dim, int degree, int n_q_points, int n_components, typename number = double> void Utils::MatrixFreeOperators::LaplaceOperatorDG< dim, degree, n_q_points, n_components, number >::Tvmult (LinearAlgebra::distributed::Vector< number > & dst, const LinearAlgebra::distributed::Vector< number > & src) const inline
Definition at line 423 of file utils.h.
References vmult_add().
Tvmult_add()
template<int dim, int degree, int n_q_points, int n_components, typename number = double> void Utils::MatrixFreeOperators::LaplaceOperatorDG< dim, degree, n_q_points, n_components, number >::Tvmult_add (LinearAlgebra::distributed::Vector< number > & dst, const LinearAlgebra::distributed::Vector< number > & src) const inline
Definition at line 431 of file utils.h.
References vmult_add().
vmult()
template<int dim, int degree, int n_q_points, int n_components, typename number = double> void Utils::MatrixFreeOperators::LaplaceOperatorDG< dim, degree, n_q_points, n_components, number >::vmult (LinearAlgebra::distributed::Vector< number > & dst, const LinearAlgebra::distributed::Vector< number > & src) const inline
Definition at line 415 of file utils.h.
References vmult_add().
vmult_add()
template<int dim, int degree, int n_q_points, int n_components, typename number = double> void Utils::MatrixFreeOperators::LaplaceOperatorDG< dim, degree, n_q_points, n_components, number >::vmult_add (LinearAlgebra::distributed::Vector< number > & dst, const LinearAlgebra::distributed::Vector< number > & src) const inline
Definition at line 438 of file utils.h.
References data, local_apply(), local_apply_boundary(), local_apply_face(), LinearAlgebra::distributed::Vector< typename Number, typename MemorySpace >::partitioners_are_globally_compatible(), LinearAlgebra::distributed::Vector< typename Number, typename MemorySpace >::reinit(), LinearAlgebra::distributed::Vector< typename Number, typename MemorySpace >::swap(), and LinearAlgebra::distributed::Vector< typename Number, typename MemorySpace >::zero_out_ghost_values().
Referenced by Tvmult(), Tvmult_add(), and vmult().
Member Data Documentation
constraints
template<int dim, int degree, int n_q_points, int n_components, typename number = double> AffineConstraints<number> Utils::MatrixFreeOperators::LaplaceOperatorDG< dim, degree, n_q_points, n_components, number >::constraints private
Definition at line 1100 of file utils.h.
Referenced by get_system_matrix(), get_system_matrix(), and reinit().
data
template<int dim, int degree, int n_q_points, int n_components, typename number = double> MatrixFree<dim, number> Utils::MatrixFreeOperators::LaplaceOperatorDG< dim, degree, n_q_points, n_components, number >::data private
Definition at line 1096 of file utils.h.
Referenced by compute_inverse_diagonal(), get_dof_handler(), get_matrix_free(), get_system_matrix(), get_system_matrix(), get_triangulation(), initialize_dof_vector(), local_apply(), local_apply_boundary(), local_apply_face(), local_diagonal_boundary(), local_diagonal_cell(), local_diagonal_face(), m(), n(), reinit(), rhs(), and vmult_add().
fe_degree
template<int dim, int degree, int n_q_points, int n_components, typename number = double> int Utils::MatrixFreeOperators::LaplaceOperatorDG< dim, degree, n_q_points, n_components, number >::fe_degree private
Definition at line 1098 of file utils.h.
Referenced by get_system_matrix(), get_system_matrix(), local_apply_boundary(), local_apply_face(), local_diagonal_boundary(), local_diagonal_face(), and reinit().
inverse_diagonal_entries
template<int dim, int degree, int n_q_points, int n_components, typename number = double> LinearAlgebra::distributed::Vector<number> Utils::MatrixFreeOperators::LaplaceOperatorDG< dim, degree, n_q_points, n_components, number >::inverse_diagonal_entries private
Definition at line 1097 of file utils.h.
Referenced by compute_inverse_diagonal(), and get_matrix_diagonal_inverse().
system_matrix
template<int dim, int degree, int n_q_points, int n_components, typename number = double> TrilinosWrappers::SparseMatrix Utils::MatrixFreeOperators::LaplaceOperatorDG< dim, degree, n_q_points, n_components, number >::system_matrix mutable private
Definition at line 1099 of file utils.h.
Referenced by get_system_matrix().
The documentation for this class was generated from the following file:
/github/workspace/include/utils.h