PolyDEAL: internal::LinearOperatorMGImplementation::MatrixInterfaceWithoutVmultAdd< Range, Domain, Payload > Class Template Reference
internal::LinearOperatorMGImplementation::MatrixInterfaceWithoutVmultAdd< Range, Domain, Payload > Class Template Reference
#include <linear_operator_for_mg.h>
Public Member Functions
template<typename Matrix >
void operator() (LinearOperatorMG< Range, Domain, Payload > &op, const Matrix &matrix)
Detailed Description
template<typename Range, typename Domain, typename Payload>
class internal::LinearOperatorMGImplementation::MatrixInterfaceWithoutVmultAdd< Range, Domain, Payload >
Definition at line 1256 of file linear_operator_for_mg.h.
Member Function Documentation
operator()()
template<typename Range , typename Domain , typename Payload > template<typename Matrix > void internal::LinearOperatorMGImplementation::MatrixInterfaceWithoutVmultAdd< Range, Domain, Payload >::operator() (LinearOperatorMG< Range, Domain, Payload > & op, const Matrix & matrix) inline
Definition at line 1261 of file linear_operator_for_mg.h.
References internal::LinearOperatorMGImplementation::apply_with_intermediate_storage(), b(), PointerComparison::equal(), LinearOperatorMG< Range, Domain, Payload >::Tvmult, LinearOperatorMG< Range, Domain, Payload >::Tvmult_add, LinearOperatorMG< Range, Domain, Payload >::vmult, and LinearOperatorMG< Range, Domain, Payload >::vmult_add.
The documentation for this class was generated from the following file:
/github/workspace/include/linear_operator_for_mg.h