PolyDEAL: Utils::MatrixFreeOperators::MonodomainOperatorDG< dim, degree, n_q_points, n_components, number > Class Template Reference
Utils::MatrixFreeOperators::MonodomainOperatorDG< dim, degree, n_q_points, n_components, number > Class Template Reference
#include <utils.h>
Public Types
using value_type = number
using VectorizedArrayType = VectorizedArray<number>
using VectorType = LinearAlgebra::distributed::Vector<number>
Public Member Functions
MonodomainOperatorDG (const Physics::BilinearFormParameters &parameters_)
void reinit (const Mapping< dim > &mapping, const DoFHandler< dim > &dof_handler, const unsigned int level=numbers::invalid_unsigned_int)
void vmult (LinearAlgebra::distributed::Vector< number > &dst, const LinearAlgebra::distributed::Vector< number > &src) const
void Tvmult (LinearAlgebra::distributed::Vector< number > &dst, const LinearAlgebra::distributed::Vector< number > &src) const
void Tvmult_add (LinearAlgebra::distributed::Vector< number > &dst, const LinearAlgebra::distributed::Vector< number > &src) const
void vmult_add (LinearAlgebra::distributed::Vector< number > &dst, const LinearAlgebra::distributed::Vector< number > &src) const
types::global_dof_index m () const
types::global_dof_index n () const
number el (const unsigned int row, const unsigned int col) const
void initialize_dof_vector (LinearAlgebra::distributed::Vector< number > &vector) const
const DoFHandler< dim > & get_dof_handler () const
const Triangulation< dim > & get_triangulation () const
const LinearAlgebra::distributed::Vector< number > & get_matrix_diagonal_inverse () const
const MatrixFree< dim, number > * get_matrix_free () const
const TrilinosWrappers::SparseMatrix & get_system_matrix () const
void get_system_matrix (TrilinosWrappers::SparseMatrix &mg_matrix) const
void compute_inverse_diagonal ()
void apply_mass_term (LinearAlgebra::distributed::Vector< number > &dst, const LinearAlgebra::distributed::Vector< number > &src) const
void rhs (LinearAlgebra::distributed::Vector< number > &rhs, const LinearAlgebra::distributed::Vector< number > &solution_minus_ion, const Function< dim > &Iext) const
Public Member Functions inherited from EnableObserverPointer
EnableObserverPointer ()
EnableObserverPointer (const EnableObserverPointer &)
EnableObserverPointer (EnableObserverPointer &&) noexcept
virtual ~EnableObserverPointer ()
EnableObserverPointer & operator= (const EnableObserverPointer &)
EnableObserverPointer & operator= (EnableObserverPointer &&) noexcept
void serialize (Archive &ar, const unsigned int version)
unsigned int n_subscriptions () const
void list_subscribers (StreamType &stream) const
void list_subscribers () const
unsigned int n_subscriptions () const
void list_subscribers (StreamType &stream) const
void list_subscribers () const
Private Member Functions
void local_apply (const MatrixFree< dim, number > &data, LinearAlgebra::distributed::Vector< number > &dst, const LinearAlgebra::distributed::Vector< number > &src, const std::pair< unsigned int, unsigned int > &cell_range) const
void local_apply_face (const MatrixFree< dim, number > &data, LinearAlgebra::distributed::Vector< number > &dst, const LinearAlgebra::distributed::Vector< number > &src, const std::pair< unsigned int, unsigned int > &face_range) const
void local_apply_boundary (const MatrixFree< dim, number > &data, LinearAlgebra::distributed::Vector< number > &dst, const LinearAlgebra::distributed::Vector< number > &src, const std::pair< unsigned int, unsigned int > &face_range) const
void local_diagonal_cell (const MatrixFree< dim, number > &data, LinearAlgebra::distributed::Vector< number > &dst, const unsigned int &, const std::pair< unsigned int, unsigned int > &cell_range) const
void local_diagonal_face (const MatrixFree< dim, number > &data, LinearAlgebra::distributed::Vector< number > &dst, const unsigned int &, const std::pair< unsigned int, unsigned int > &face_range) const
void local_diagonal_boundary (const MatrixFree< dim, number > &data, LinearAlgebra::distributed::Vector< number > &dst, const unsigned int &, const std::pair< unsigned int, unsigned int > &face_range) const
Private Attributes
MatrixFree< dim, number > data
LinearAlgebra::distributed::Vector< number > inverse_diagonal_entries
int fe_degree
TrilinosWrappers::SparseMatrix system_matrix
AffineConstraints< number > constraints
Physics::BilinearFormParameters parameters
double factor
Additional Inherited Members
Static Public Member Functions inherited from EnableObserverPointer
static ::ExceptionBase & ExcInUse (int arg1, std::string arg2, std::string arg3)
static ::ExceptionBase & ExcNoSubscriber (std::string arg1, std::string arg2)
Detailed Description
template<int dim, int degree, int n_q_points, int n_components, typename number = double>
class Utils::MatrixFreeOperators::MonodomainOperatorDG< dim, degree, n_q_points, n_components, number >
Action of SIPDG form on a vector for the monodomain problem.
Definition at line 1121 of file utils.h.
Member Typedef Documentation
value_type
template<int dim, int degree, int n_q_points, int n_components, typename number = double> using Utils::MatrixFreeOperators::MonodomainOperatorDG< dim, degree, n_q_points, n_components, number >::value_type = number
Definition at line 1124 of file utils.h.
VectorizedArrayType
template<int dim, int degree, int n_q_points, int n_components, typename number = double> using Utils::MatrixFreeOperators::MonodomainOperatorDG< dim, degree, n_q_points, n_components, number >::VectorizedArrayType = VectorizedArray<number>
Definition at line 1125 of file utils.h.
VectorType
template<int dim, int degree, int n_q_points, int n_components, typename number = double> using Utils::MatrixFreeOperators::MonodomainOperatorDG< dim, degree, n_q_points, n_components, number >::VectorType = LinearAlgebra::distributed::Vector<number>
Definition at line 1126 of file utils.h.
Constructor & Destructor Documentation
MonodomainOperatorDG()
template<int dim, int degree, int n_q_points, int n_components, typename number = double> Utils::MatrixFreeOperators::MonodomainOperatorDG< dim, degree, n_q_points, n_components, number >::MonodomainOperatorDG (const Physics::BilinearFormParameters & parameters_) inline
Definition at line 1128 of file utils.h.
References Utils::Physics::BDF1, Utils::Physics::BDF2, factor, and parameters.
Member Function Documentation
apply_mass_term()
template<int dim, int degree, int n_q_points, int n_components, typename number = double> void Utils::MatrixFreeOperators::MonodomainOperatorDG< dim, degree, n_q_points, n_components, number >::apply_mass_term (LinearAlgebra::distributed::Vector< number > & dst, const LinearAlgebra::distributed::Vector< number > & src) const inline
Definition at line 1500 of file utils.h.
References VectorOperation::add, LinearAlgebra::distributed::Vector< typename Number, typename MemorySpace >::compress(), data, FEEvaluation< int dim, int fe_degree, int n_q_points_1d, int n_components_, typename Number, typename VectorizedArrayType >::distribute_local_to_global(), FEEvaluation< int dim, int fe_degree, int n_q_points_1d, int n_components_, typename Number, typename VectorizedArrayType >::evaluate(), factor, FEEvaluation< int dim, int fe_degree, int n_q_points_1d, int n_components_, typename Number, typename VectorizedArrayType >::get_value(), FEEvaluation< int dim, int fe_degree, int n_q_points_1d, int n_components_, typename Number, typename VectorizedArrayType >::integrate(), FEEvaluation< int dim, int fe_degree, int n_q_points_1d, int n_components_, typename Number, typename VectorizedArrayType >::n_q_points, FEEvaluation< int dim, int fe_degree, int n_q_points_1d, int n_components_, typename Number, typename VectorizedArrayType >::read_dof_values(), FEEvaluation< int dim, int fe_degree, int n_q_points_1d, int n_components_, typename Number, typename VectorizedArrayType >::reinit(), FEEvaluation< int dim, int fe_degree, int n_q_points_1d, int n_components_, typename Number, typename VectorizedArrayType >::submit_value(), and EvaluationFlags::values.
compute_inverse_diagonal()
template<int dim, int degree, int n_q_points, int n_components, typename number = double> void Utils::MatrixFreeOperators::MonodomainOperatorDG< dim, degree, n_q_points, n_components, number >::compute_inverse_diagonal () inline
Definition at line 1478 of file utils.h.
References std::abs(), data, inverse_diagonal_entries, local_diagonal_boundary(), local_diagonal_cell(), and local_diagonal_face().
Referenced by reinit().
el()
template<int dim, int degree, int n_q_points, int n_components, typename number = double> number Utils::MatrixFreeOperators::MonodomainOperatorDG< dim, degree, n_q_points, n_components, number >::el (const unsigned int row, const unsigned int col) const inline
Definition at line 1238 of file utils.h.
get_dof_handler()
template<int dim, int degree, int n_q_points, int n_components, typename number = double> const DoFHandler< dim > & Utils::MatrixFreeOperators::MonodomainOperatorDG< dim, degree, n_q_points, n_components, number >::get_dof_handler () const inline
Definition at line 1256 of file utils.h.
References data.
get_matrix_diagonal_inverse()
template<int dim, int degree, int n_q_points, int n_components, typename number = double> const LinearAlgebra::distributed::Vector< number > & Utils::MatrixFreeOperators::MonodomainOperatorDG< dim, degree, n_q_points, n_components, number >::get_matrix_diagonal_inverse () const inline
Definition at line 1269 of file utils.h.
References inverse_diagonal_entries.
get_matrix_free()
template<int dim, int degree, int n_q_points, int n_components, typename number = double> const MatrixFree< dim, number > * Utils::MatrixFreeOperators::MonodomainOperatorDG< dim, degree, n_q_points, n_components, number >::get_matrix_free () const inline
Definition at line 1276 of file utils.h.
References data.
get_system_matrix() [1/2]
template<int dim, int degree, int n_q_points, int n_components, typename number = double> const TrilinosWrappers::SparseMatrix & Utils::MatrixFreeOperators::MonodomainOperatorDG< dim, degree, n_q_points, n_components, number >::get_system_matrix () const inline
Definition at line 1284 of file utils.h.
References std::abs(), TrilinosWrappers::SparsityPattern::compress(), MatrixFreeTools::compute_matrix(), constraints, data, factor, fe_degree, EvaluationFlags::gradients, numbers::invalid_unsigned_int, DoFTools::make_flux_sparsity_pattern(), MGTools::make_flux_sparsity_pattern(), std::max(), parameters, system_matrix, and EvaluationFlags::values.
get_system_matrix() [2/2]
template<int dim, int degree, int n_q_points, int n_components, typename number = double> void Utils::MatrixFreeOperators::MonodomainOperatorDG< dim, degree, n_q_points, n_components, number >::get_system_matrix (TrilinosWrappers::SparseMatrix & mg_matrix) const inline
Definition at line 1389 of file utils.h.
References std::abs(), MatrixFreeTools::compute_matrix(), constraints, data, SparsityTools::distribute_sparsity_pattern(), DoFTools::extract_locally_relevant_dofs(), factor, fe_degree, EvaluationFlags::gradients, DoFHandler< int dim, int spacedim >::locally_owned_dofs(), TrilinosWrappers::SparseMatrix::m(), DoFTools::make_flux_sparsity_pattern(), std::max(), TrilinosWrappers::SparseMatrix::n(), DoFHandler< int dim, int spacedim >::n_dofs(), parameters, TrilinosWrappers::SparseMatrix::reinit(), and EvaluationFlags::values.
get_triangulation()
template<int dim, int degree, int n_q_points, int n_components, typename number = double> const Triangulation< dim > & Utils::MatrixFreeOperators::MonodomainOperatorDG< dim, degree, n_q_points, n_components, number >::get_triangulation () const inline
Definition at line 1263 of file utils.h.
References data.
initialize_dof_vector()
template<int dim, int degree, int n_q_points, int n_components, typename number = double> void Utils::MatrixFreeOperators::MonodomainOperatorDG< dim, degree, n_q_points, n_components, number >::initialize_dof_vector (LinearAlgebra::distributed::Vector< number > & vector) const inline
Definition at line 1248 of file utils.h.
References data.
local_apply()
template<int dim, int degree, int n_q_points, int n_components, typename number = double> void Utils::MatrixFreeOperators::MonodomainOperatorDG< dim, degree, n_q_points, n_components, number >::local_apply (const MatrixFree< dim, number > & data, LinearAlgebra::distributed::Vector< number > & dst, const LinearAlgebra::distributed::Vector< number > & src, const std::pair< unsigned int, unsigned int > & cell_range) const inline private
Definition at line 1565 of file utils.h.
References data, FEEvaluation< int dim, int fe_degree, int n_q_points_1d, int n_components_, typename Number, typename VectorizedArrayType >::distribute_local_to_global(), FEEvaluation< int dim, int fe_degree, int n_q_points_1d, int n_components_, typename Number, typename VectorizedArrayType >::evaluate(), factor, FEEvaluation< int dim, int fe_degree, int n_q_points_1d, int n_components_, typename Number, typename VectorizedArrayType >::get_gradient(), FEEvaluation< int dim, int fe_degree, int n_q_points_1d, int n_components_, typename Number, typename VectorizedArrayType >::get_value(), EvaluationFlags::gradients, FEEvaluation< int dim, int fe_degree, int n_q_points_1d, int n_components_, typename Number, typename VectorizedArrayType >::integrate(), FEEvaluation< int dim, int fe_degree, int n_q_points_1d, int n_components_, typename Number, typename VectorizedArrayType >::n_q_points, parameters, FEEvaluation< int dim, int fe_degree, int n_q_points_1d, int n_components_, typename Number, typename VectorizedArrayType >::read_dof_values(), FEEvaluation< int dim, int fe_degree, int n_q_points_1d, int n_components_, typename Number, typename VectorizedArrayType >::reinit(), FEEvaluation< int dim, int fe_degree, int n_q_points_1d, int n_components_, typename Number, typename VectorizedArrayType >::submit_gradient(), FEEvaluation< int dim, int fe_degree, int n_q_points_1d, int n_components_, typename Number, typename VectorizedArrayType >::submit_value(), and EvaluationFlags::values.
Referenced by vmult_add().
local_apply_boundary()
template<int dim, int degree, int n_q_points, int n_components, typename number = double> void Utils::MatrixFreeOperators::MonodomainOperatorDG< dim, degree, n_q_points, n_components, number >::local_apply_boundary (const MatrixFree< dim, number > & data, LinearAlgebra::distributed::Vector< number > & dst, const LinearAlgebra::distributed::Vector< number > & src, const std::pair< unsigned int, unsigned int > & face_range) const inline private
Definition at line 1648 of file utils.h.
References data.
Referenced by vmult_add().
local_apply_face()
template<int dim, int degree, int n_q_points, int n_components, typename number = double> void Utils::MatrixFreeOperators::MonodomainOperatorDG< dim, degree, n_q_points, n_components, number >::local_apply_face (const MatrixFree< dim, number > & data, LinearAlgebra::distributed::Vector< number > & dst, const LinearAlgebra::distributed::Vector< number > & src, const std::pair< unsigned int, unsigned int > & face_range) const inline private
Definition at line 1589 of file utils.h.
References std::abs(), data, FEFaceEvaluation< int dim, int fe_degree, int n_q_points_1d, int n_components_, typename Number, typename VectorizedArrayType >::distribute_local_to_global(), FEFaceEvaluation< int dim, int fe_degree, int n_q_points_1d, int n_components_, typename Number, typename VectorizedArrayType >::evaluate(), fe_degree, FEFaceEvaluation< int dim, int fe_degree, int n_q_points_1d, int n_components_, typename Number, typename VectorizedArrayType >::get_normal_derivative(), FEFaceEvaluation< int dim, int fe_degree, int n_q_points_1d, int n_components_, typename Number, typename VectorizedArrayType >::get_value(), EvaluationFlags::gradients, FEFaceEvaluation< int dim, int fe_degree, int n_q_points_1d, int n_components_, typename Number, typename VectorizedArrayType >::integrate(), FEFaceEvaluation< int dim, int fe_degree, int n_q_points_1d, int n_components_, typename Number, typename VectorizedArrayType >::inverse_jacobian(), std::max(), FEFaceEvaluation< int dim, int fe_degree, int n_q_points_1d, int n_components_, typename Number, typename VectorizedArrayType >::n_q_points, FEFaceEvaluation< int dim, int fe_degree, int n_q_points_1d, int n_components_, typename Number, typename VectorizedArrayType >::normal_vector(), parameters, FEFaceEvaluation< int dim, int fe_degree, int n_q_points_1d, int n_components_, typename Number, typename VectorizedArrayType >::read_dof_values(), FEFaceEvaluation< int dim, int fe_degree, int n_q_points_1d, int n_components_, typename Number, typename VectorizedArrayType >::reinit(), FEFaceEvaluation< int dim, int fe_degree, int n_q_points_1d, int n_components_, typename Number, typename VectorizedArrayType >::submit_normal_derivative(), FEFaceEvaluation< int dim, int fe_degree, int n_q_points_1d, int n_components_, typename Number, typename VectorizedArrayType >::submit_value(), and EvaluationFlags::values.
Referenced by vmult_add().
local_diagonal_boundary()
template<int dim, int degree, int n_q_points, int n_components, typename number = double> void Utils::MatrixFreeOperators::MonodomainOperatorDG< dim, degree, n_q_points, n_components, number >::local_diagonal_boundary (const MatrixFree< dim, number > & data, LinearAlgebra::distributed::Vector< number > & dst, const unsigned int & , const std::pair< unsigned int, unsigned int > & face_range) const inline private
Definition at line 1800 of file utils.h.
References data.
Referenced by compute_inverse_diagonal().
local_diagonal_cell()
template<int dim, int degree, int n_q_points, int n_components, typename number = double> void Utils::MatrixFreeOperators::MonodomainOperatorDG< dim, degree, n_q_points, n_components, number >::local_diagonal_cell (const MatrixFree< dim, number > & data, LinearAlgebra::distributed::Vector< number > & dst, const unsigned int & , const std::pair< unsigned int, unsigned int > & cell_range) const inline private
Definition at line 1663 of file utils.h.
References FEEvaluation< int dim, int fe_degree, int n_q_points_1d, int n_components_, typename Number, typename VectorizedArrayType >::begin_dof_values(), data, FEEvaluation< int dim, int fe_degree, int n_q_points_1d, int n_components_, typename Number, typename VectorizedArrayType >::distribute_local_to_global(), FEEvaluation< int dim, int fe_degree, int n_q_points_1d, int n_components_, typename Number, typename VectorizedArrayType >::dofs_per_cell, FEEvaluation< int dim, int fe_degree, int n_q_points_1d, int n_components_, typename Number, typename VectorizedArrayType >::evaluate(), factor, FEEvaluation< int dim, int fe_degree, int n_q_points_1d, int n_components_, typename Number, typename VectorizedArrayType >::get_gradient(), FEEvaluation< int dim, int fe_degree, int n_q_points_1d, int n_components_, typename Number, typename VectorizedArrayType >::get_value(), EvaluationFlags::gradients, FEEvaluation< int dim, int fe_degree, int n_q_points_1d, int n_components_, typename Number, typename VectorizedArrayType >::integrate(), FEEvaluation< int dim, int fe_degree, int n_q_points_1d, int n_components_, typename Number, typename VectorizedArrayType >::n_q_points, parameters, FEEvaluation< int dim, int fe_degree, int n_q_points_1d, int n_components_, typename Number, typename VectorizedArrayType >::reinit(), FEEvaluation< int dim, int fe_degree, int n_q_points_1d, int n_components_, typename Number, typename VectorizedArrayType >::submit_gradient(), FEEvaluation< int dim, int fe_degree, int n_q_points_1d, int n_components_, typename Number, typename VectorizedArrayType >::submit_value(), and EvaluationFlags::values.
Referenced by compute_inverse_diagonal().
local_diagonal_face()
template<int dim, int degree, int n_q_points, int n_components, typename number = double> void Utils::MatrixFreeOperators::MonodomainOperatorDG< dim, degree, n_q_points, n_components, number >::local_diagonal_face (const MatrixFree< dim, number > & data, LinearAlgebra::distributed::Vector< number > & dst, const unsigned int & , const std::pair< unsigned int, unsigned int > & face_range) const inline private
Definition at line 1702 of file utils.h.
References std::abs(), FEFaceEvaluation< int dim, int fe_degree, int n_q_points_1d, int n_components_, typename Number, typename VectorizedArrayType >::begin_dof_values(), data, FEFaceEvaluation< int dim, int fe_degree, int n_q_points_1d, int n_components_, typename Number, typename VectorizedArrayType >::distribute_local_to_global(), FEFaceEvaluation< int dim, int fe_degree, int n_q_points_1d, int n_components_, typename Number, typename VectorizedArrayType >::dofs_per_cell, FEFaceEvaluation< int dim, int fe_degree, int n_q_points_1d, int n_components_, typename Number, typename VectorizedArrayType >::evaluate(), fe_degree, FEFaceEvaluation< int dim, int fe_degree, int n_q_points_1d, int n_components_, typename Number, typename VectorizedArrayType >::get_normal_derivative(), FEFaceEvaluation< int dim, int fe_degree, int n_q_points_1d, int n_components_, typename Number, typename VectorizedArrayType >::get_value(), EvaluationFlags::gradients, FEFaceEvaluation< int dim, int fe_degree, int n_q_points_1d, int n_components_, typename Number, typename VectorizedArrayType >::integrate(), FEFaceEvaluation< int dim, int fe_degree, int n_q_points_1d, int n_components_, typename Number, typename VectorizedArrayType >::inverse_jacobian(), std::max(), FEFaceEvaluation< int dim, int fe_degree, int n_q_points_1d, int n_components_, typename Number, typename VectorizedArrayType >::n_q_points, FEFaceEvaluation< int dim, int fe_degree, int n_q_points_1d, int n_components_, typename Number, typename VectorizedArrayType >::normal_vector(), parameters, FEFaceEvaluation< int dim, int fe_degree, int n_q_points_1d, int n_components_, typename Number, typename VectorizedArrayType >::reinit(), FEFaceEvaluation< int dim, int fe_degree, int n_q_points_1d, int n_components_, typename Number, typename VectorizedArrayType >::submit_normal_derivative(), FEFaceEvaluation< int dim, int fe_degree, int n_q_points_1d, int n_components_, typename Number, typename VectorizedArrayType >::submit_value(), and EvaluationFlags::values.
Referenced by compute_inverse_diagonal().
m()
template<int dim, int degree, int n_q_points, int n_components, typename number = double> types::global_dof_index Utils::MatrixFreeOperators::MonodomainOperatorDG< dim, degree, n_q_points, n_components, number >::m () const inline
Definition at line 1226 of file utils.h.
References data.
n()
template<int dim, int degree, int n_q_points, int n_components, typename number = double> types::global_dof_index Utils::MatrixFreeOperators::MonodomainOperatorDG< dim, degree, n_q_points, n_components, number >::n () const inline
Definition at line 1232 of file utils.h.
References data.
reinit()
template<int dim, int degree, int n_q_points, int n_components, typename number = double> void Utils::MatrixFreeOperators::MonodomainOperatorDG< dim, degree, n_q_points, n_components, number >::reinit (const Mapping< dim > & mapping, const DoFHandler< dim > & dof_handler, const unsigned int level = numbers::invalid_unsigned_int) inline
Definition at line 1140 of file utils.h.
References compute_inverse_diagonal(), constraints, data, FiniteElement< int dim, int spacedim >::degree, fe_degree, DoFHandler< int dim, int spacedim >::get_fe(), numbers::invalid_unsigned_int, MatrixFree::AdditionalData::mapping_update_flags, MatrixFree::AdditionalData::mapping_update_flags_boundary_faces, MatrixFree::AdditionalData::mapping_update_flags_inner_faces, MatrixFree::AdditionalData::mg_level, MatrixFree::AdditionalData::none, MatrixFree::AdditionalData::tasks_block_size, and MatrixFree::AdditionalData::tasks_parallel_scheme.
rhs()
template<int dim, int degree, int n_q_points, int n_components, typename number = double> void Utils::MatrixFreeOperators::MonodomainOperatorDG< dim, degree, n_q_points, n_components, number >::rhs (LinearAlgebra::distributed::Vector< number > & rhs, const LinearAlgebra::distributed::Vector< number > & solution_minus_ion, const Function< dim > & Iext) const inline
Definition at line 1522 of file utils.h.
References VectorOperation::add, data, FEEvaluation< int dim, int fe_degree, int n_q_points_1d, int n_components_, typename Number, typename VectorizedArrayType >::distribute_local_to_global(), FEEvaluation< int dim, int fe_degree, int n_q_points_1d, int n_components_, typename Number, typename VectorizedArrayType >::evaluate(), FEEvaluation< int dim, int fe_degree, int n_q_points_1d, int n_components_, typename Number, typename VectorizedArrayType >::get_value(), FEEvaluation< int dim, int fe_degree, int n_q_points_1d, int n_components_, typename Number, typename VectorizedArrayType >::integrate(), FEEvaluation< int dim, int fe_degree, int n_q_points_1d, int n_components_, typename Number, typename VectorizedArrayType >::n_q_points, parameters, FEEvaluation< int dim, int fe_degree, int n_q_points_1d, int n_components_, typename Number, typename VectorizedArrayType >::quadrature_point(), FEEvaluation< int dim, int fe_degree, int n_q_points_1d, int n_components_, typename Number, typename VectorizedArrayType >::read_dof_values(), FEEvaluation< int dim, int fe_degree, int n_q_points_1d, int n_components_, typename Number, typename VectorizedArrayType >::reinit(), rhs(), FEEvaluation< int dim, int fe_degree, int n_q_points_1d, int n_components_, typename Number, typename VectorizedArrayType >::submit_value(), Function< int dim, typename RangeNumberType >::value(), and EvaluationFlags::values.
Referenced by rhs().
Tvmult()
template<int dim, int degree, int n_q_points, int n_components, typename number = double> void Utils::MatrixFreeOperators::MonodomainOperatorDG< dim, degree, n_q_points, n_components, number >::Tvmult (LinearAlgebra::distributed::Vector< number > & dst, const LinearAlgebra::distributed::Vector< number > & src) const inline
Definition at line 1178 of file utils.h.
References vmult_add().
Tvmult_add()
template<int dim, int degree, int n_q_points, int n_components, typename number = double> void Utils::MatrixFreeOperators::MonodomainOperatorDG< dim, degree, n_q_points, n_components, number >::Tvmult_add (LinearAlgebra::distributed::Vector< number > & dst, const LinearAlgebra::distributed::Vector< number > & src) const inline
Definition at line 1186 of file utils.h.
References vmult_add().
vmult()
template<int dim, int degree, int n_q_points, int n_components, typename number = double> void Utils::MatrixFreeOperators::MonodomainOperatorDG< dim, degree, n_q_points, n_components, number >::vmult (LinearAlgebra::distributed::Vector< number > & dst, const LinearAlgebra::distributed::Vector< number > & src) const inline
Definition at line 1170 of file utils.h.
References vmult_add().
vmult_add()
template<int dim, int degree, int n_q_points, int n_components, typename number = double> void Utils::MatrixFreeOperators::MonodomainOperatorDG< dim, degree, n_q_points, n_components, number >::vmult_add (LinearAlgebra::distributed::Vector< number > & dst, const LinearAlgebra::distributed::Vector< number > & src) const inline
Definition at line 1193 of file utils.h.
References data, local_apply(), local_apply_boundary(), local_apply_face(), LinearAlgebra::distributed::Vector< typename Number, typename MemorySpace >::partitioners_are_globally_compatible(), LinearAlgebra::distributed::Vector< typename Number, typename MemorySpace >::reinit(), LinearAlgebra::distributed::Vector< typename Number, typename MemorySpace >::swap(), and LinearAlgebra::distributed::Vector< typename Number, typename MemorySpace >::zero_out_ghost_values().
Referenced by Tvmult(), Tvmult_add(), and vmult().
Member Data Documentation
constraints
template<int dim, int degree, int n_q_points, int n_components, typename number = double> AffineConstraints<number> Utils::MatrixFreeOperators::MonodomainOperatorDG< dim, degree, n_q_points, n_components, number >::constraints private
Definition at line 1818 of file utils.h.
Referenced by get_system_matrix(), get_system_matrix(), and reinit().
data
template<int dim, int degree, int n_q_points, int n_components, typename number = double> MatrixFree<dim, number> Utils::MatrixFreeOperators::MonodomainOperatorDG< dim, degree, n_q_points, n_components, number >::data private
Definition at line 1814 of file utils.h.
Referenced by apply_mass_term(), compute_inverse_diagonal(), get_dof_handler(), get_matrix_free(), get_system_matrix(), get_system_matrix(), get_triangulation(), initialize_dof_vector(), local_apply(), local_apply_boundary(), local_apply_face(), local_diagonal_boundary(), local_diagonal_cell(), local_diagonal_face(), m(), n(), reinit(), rhs(), and vmult_add().
factor
template<int dim, int degree, int n_q_points, int n_components, typename number = double> double Utils::MatrixFreeOperators::MonodomainOperatorDG< dim, degree, n_q_points, n_components, number >::factor private
Definition at line 1820 of file utils.h.
Referenced by apply_mass_term(), get_system_matrix(), get_system_matrix(), local_apply(), local_diagonal_cell(), and MonodomainOperatorDG().
fe_degree
template<int dim, int degree, int n_q_points, int n_components, typename number = double> int Utils::MatrixFreeOperators::MonodomainOperatorDG< dim, degree, n_q_points, n_components, number >::fe_degree private
Definition at line 1816 of file utils.h.
Referenced by get_system_matrix(), get_system_matrix(), local_apply_face(), local_diagonal_face(), and reinit().
inverse_diagonal_entries
template<int dim, int degree, int n_q_points, int n_components, typename number = double> LinearAlgebra::distributed::Vector<number> Utils::MatrixFreeOperators::MonodomainOperatorDG< dim, degree, n_q_points, n_components, number >::inverse_diagonal_entries private
Definition at line 1815 of file utils.h.
Referenced by compute_inverse_diagonal(), and get_matrix_diagonal_inverse().
parameters
template<int dim, int degree, int n_q_points, int n_components, typename number = double> Physics::BilinearFormParameters Utils::MatrixFreeOperators::MonodomainOperatorDG< dim, degree, n_q_points, n_components, number >::parameters private
Definition at line 1819 of file utils.h.
Referenced by get_system_matrix(), get_system_matrix(), local_apply(), local_apply_face(), local_diagonal_cell(), local_diagonal_face(), MonodomainOperatorDG(), and rhs().
system_matrix
template<int dim, int degree, int n_q_points, int n_components, typename number = double> TrilinosWrappers::SparseMatrix Utils::MatrixFreeOperators::MonodomainOperatorDG< dim, degree, n_q_points, n_components, number >::system_matrix mutable private
Definition at line 1817 of file utils.h.
Referenced by get_system_matrix().
The documentation for this class was generated from the following file:
/github/workspace/include/utils.h