PolyDEAL: dealii::internal::AgglomerationHandlerImplementation< dim, spacedim > Class Template Reference
dealii::internal::AgglomerationHandlerImplementation< dim, spacedim > Class Template Reference
Static Public Member Functions
static const FEValuesBase< dim, spacedim > & reinit_master (const typename DoFHandler< dim, spacedim >::active_cell_iterator &cell, const unsigned int face_index, std::unique_ptr< NonMatching::FEImmersedSurfaceValues< spacedim > > &agglo_isv_ptr, const AgglomerationHandler< dim, spacedim > &handler)
static void setup_master_neighbor_connectivity (const typename Triangulation< dim, spacedim >::active_cell_iterator &master_cell, const AgglomerationHandler< dim, spacedim > &handler)
Detailed Description
template<int dim, int spacedim>
class dealii::internal::AgglomerationHandlerImplementation< dim, spacedim >
Helper class to reinit finite element spaces on polytopal cells.
Definition at line 1100 of file agglomeration_handler.cc.
Member Function Documentation
reinit_master()
template<int dim, int spacedim> const FEValuesBase< dim, spacedim > & dealii::internal::AgglomerationHandlerImplementation< dim, spacedim >::reinit_master (const typename DoFHandler< dim, spacedim >::active_cell_iterator & cell, const unsigned int face_index, std::unique_ptr< NonMatching::FEImmersedSurfaceValues< spacedim > > & agglo_isv_ptr, const AgglomerationHandler< dim, spacedim > & handler) inline static
Definition at line 1104 of file agglomeration_handler.cc.
References AgglomerationHandler< dim, spacedim >::agglomeration_face_flags, AgglomerationHandler< dim, spacedim >::agglomeration_face_quad, AgglomerationHandler< dim, spacedim >::agglomeration_face_quad_collection, AgglomerationHandler< dim, spacedim >::box_mapping, DoFHandler< int dim, int spacedim >::get_fe(), AgglomerationHandler< dim, spacedim >::hp_no_face_values, AgglomerationHandler< dim, spacedim >::is_hp_collection, AgglomerationHandler< dim, spacedim >::is_master_cell(), AgglomerationHandler< dim, spacedim >::master2polygon, AgglomerationAccessor< dim, spacedim >::neighbor(), AgglomerationHandler< dim, spacedim >::no_face_values, AgglomerationHandler< dim, spacedim >::polytope_cache, hp::QCollection< int dim >::size(), Quadrature< int dim >::size(), and IteratorState::valid.
Referenced by AgglomerationHandler< dim, spacedim >::reinit(), AgglomerationHandler< dim, spacedim >::reinit_interface(), and AgglomerationHandler< dim, spacedim >::reinit_master().
setup_master_neighbor_connectivity()
template<int dim, int spacedim> void dealii::internal::AgglomerationHandlerImplementation< dim, spacedim >::setup_master_neighbor_connectivity (const typename Triangulation< dim, spacedim >::active_cell_iterator & master_cell, const AgglomerationHandler< dim, spacedim > & handler) inline static
Given an agglomeration described by the master cell master_cell, this function:
enumerates the faces of the agglomeration
stores who is the neighbor, the local face indices from outside and inside
Definition at line 1254 of file agglomeration_handler.cc.
References AgglomerationHandler< dim, spacedim >::are_cells_agglomerated(), AgglomerationHandler< dim, spacedim >::get_agglomerate(), AgglomerationHandler< dim, spacedim >::is_slave_cell(), AgglomerationHandler< dim, spacedim >::master2polygon, AgglomerationHandler< dim, spacedim >::master_slave_relationships, AgglomerationHandler< dim, spacedim >::master_slave_relationships_iterators, AgglomerationHandler< dim, spacedim >::number_of_agglomerated_faces, AgglomerationHandler< dim, spacedim >::polygon_boundary, AgglomerationHandler< dim, spacedim >::polytope_cache, and IteratorState::valid.
Referenced by AgglomerationHandler< dim, spacedim >::setup_connectivity_of_agglomeration().
The documentation for this class was generated from the following file:
/github/workspace/source/agglomeration_handler.cc