PolyDEAL: /github/workspace/source/mapping_box.cc File Reference
mapping_box.cc File Reference
#include <deal.II/base/array_view.h>
#include <deal.II/base/memory_consumption.h>
#include <deal.II/base/qprojector.h>
#include <deal.II/base/quadrature.h>
#include <deal.II/base/signaling_nan.h>
#include <deal.II/base/tensor.h>
#include <deal.II/dofs/dof_accessor.h>
#include <deal.II/fe/fe_values.h>
#include <deal.II/grid/tria.h>
#include <deal.II/grid/tria_iterator.h>
#include <deal.II/lac/full_matrix.h>
#include <mapping_box.h>
#include <algorithm>
Functions
DEAL_II_NAMESPACE_OPEN DeclExceptionMsg (ExcCellNotAssociatedWithBox, "You are using MappingBox, but the incoming element is not associated with a" "Bounding Box Cartesian.")
template<typename CellType>
bool has_box (const CellType &cell, const std::map< types::global_cell_index, types::global_cell_index > &translator)
Function Documentation
DeclExceptionMsg()
DEAL_II_NAMESPACE_OPEN DeclExceptionMsg (ExcCellNotAssociatedWithBox , "You are using MappingBox, but the incoming element is not associated with a" "Bounding Box Cartesian.")
References DeclExceptionMsg().
Referenced by DeclExceptionMsg().
has_box()
template<typename CellType> bool has_box (const CellType & cell, const std::map< types::global_cell_index, types::global_cell_index > & translator)
Return whether the incoming element has a BoundingBox associated to it. Simplicial and quad-hex meshes are supported.
Definition at line 52 of file mapping_box.cc.
Referenced by MappingBox< dim, spacedim >::fill_fe_immersed_surface_values(), MappingBox< dim, spacedim >::fill_fe_values(), MappingBox< dim, spacedim >::transform_points_real_to_unit_cell(), MappingBox< dim, spacedim >::transform_real_to_unit_cell(), and MappingBox< dim, spacedim >::transform_unit_to_real_cell().