PolyDEAL: dealii::PolyUtils::internal Namespace Reference
dealii::PolyUtils::internal Namespace Reference
Functions
types::global_cell_index get_index (const std::vector< types::global_cell_index > &v, const types::global_cell_index index)
template<int dim, int spacedim>
void get_face_connectivity_of_cells (const parallel::fullydistributed::Triangulation< dim, spacedim > &triangulation, DynamicSparsityPattern &cell_connectivity, const std::vector< types::global_cell_index > locally_owned_cells)
template<int dim, int spacedim, typename VectorType >
void interpolate_to_fine_grid (const AgglomerationHandler< dim, spacedim > &agglomeration_handler, VectorType &dst, const VectorType &src)
Function Documentation
get_face_connectivity_of_cells()
template<int dim, int spacedim> void dealii::PolyUtils::internal::get_face_connectivity_of_cells (const parallel::fullydistributed::Triangulation< dim, spacedim > & triangulation, DynamicSparsityPattern & cell_connectivity, const std::vector< types::global_cell_index > locally_owned_cells)
Compute the connectivity graph for locally owned regions of a distributed triangulation.
Definition at line 97 of file poly_utils.h.
References DynamicSparsityPattern::add(), get_index(), DynamicSparsityPattern::reinit(), and triangulation.
Referenced by dealii::PolyUtils::partition_locally_owned_regions().
get_index()
types::global_cell_index dealii::PolyUtils::internal::get_index (const std::vector< types::global_cell_index > & v, const types::global_cell_index index) inline
Helper function to compute the position of index index in vector v.
Definition at line 83 of file poly_utils.h.
Referenced by get_face_connectivity_of_cells(), and dealii::PolyUtils::partition_locally_owned_regions().
interpolate_to_fine_grid()
template<int dim, int spacedim, typename VectorType > void dealii::PolyUtils::internal::interpolate_to_fine_grid (const AgglomerationHandler< dim, spacedim > & agglomeration_handler, VectorType & dst, const VectorType & src)
Same as the public free function with the same name, but storing explicitly the interpolation matrix and performing interpolation through matrix-vector product.
Definition at line 849 of file poly_utils.h.
References DoFHandler< int dim, int spacedim >::active_cell_iterators(), VectorOperation::add, DynamicSparsityPattern::add_entries(), AgglomerationHandler< dim, spacedim >::agglo_dh, Triangulation< int dim, int spacedim >::all_reference_cells_are_hyper_cube(), Triangulation< int dim, int spacedim >::all_reference_cells_are_simplex(), Assert, AssertThrow, AgglomerationHandler< dim, spacedim >::cell_to_polytope_index(), AffineConstraints< typename number >::close(), DoFHandler< int dim, int spacedim >::distribute_dofs(), AffineConstraints< typename number >::distribute_local_to_global(), SparsityTools::distribute_sparsity_pattern(), FEValues< int dim, int spacedim >::dof_indices(), DoFTools::extract_locally_relevant_dofs(), Triangulation< int dim, int spacedim >::get_communicator(), AgglomerationHandler< dim, spacedim >::get_fe(), AgglomerationHandler< dim, spacedim >::get_local_bboxes(), AgglomerationHandler< dim, spacedim >::get_mapping(), FEValues< int dim, int spacedim >::get_quadrature_points(), AgglomerationHandler< dim, spacedim >::get_slaves_of_idx(), AgglomerationHandler< dim, spacedim >::get_triangulation(), AgglomerationHandler< dim, spacedim >::is_master_cell(), DoFHandler< int dim, int spacedim >::locally_owned_dofs(), DoFHandler< int dim, int spacedim >::n_dofs(), AgglomerationHandler< dim, spacedim >::output_dh, BoundingBox< int spacedim, typename Number >::real_to_unit(), DoFHandler< int dim, int spacedim >::reinit(), FEValues< int dim, int spacedim >::reinit(), and update_quadrature_points.
Referenced by dealii::PolyUtils::interpolate_to_fine_grid().