name: Indent

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Check indentation
      run: |
         ./scripts/dr.sh ./scripts/check_indentation.sh 